// GENERATED by tools/ratings.js (16 bouts a corner against each reference, 8 against each of two nearest-rated and 4 drawn at random) — do not edit by hand; re-run the tool.
// Score = strength fitted to all those bouts at once (Bradley-Terry), Maximus held at 100: ∝ inferred K/D.
export const RATINGS = {
 "references": [
  "maximus",
  "monk"
 ],
 "bouts": 16,
 "crossBouts": 8,
 "characters": {
  "plate": {
   "title": "Sir Edric",
   "type": "longsword|knight",
   "records": {
    "maximus": {
     "wins": 20,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 116,
   "provisional": 162,
   "kd": {
    "maximus": 1.64,
    "monk": 65
   }
  },
  "joan": {
   "title": "Joan of Arc",
   "type": "joan|joan",
   "records": {
    "maximus": {
     "wins": 13,
     "losses": 19,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 54,
   "provisional": 73,
   "kd": {
    "maximus": 0.692,
    "monk": 65
   }
  },
  "crossbowman": {
   "title": "Ottone Doria",
   "type": "crossbow|footman",
   "records": {
    "maximus": {
     "wins": 23,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 62,
   "provisional": 209,
   "kd": {
    "maximus": 2.474,
    "monk": 21
   }
  },
  "tosei": {
   "title": "Date Masamune",
   "type": "katana|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 86,
   "provisional": 41,
   "kd": {
    "maximus": 0.347,
    "monk": 65
   }
  },
  "hammer": {
   "title": "Gunnar Holt",
   "type": "warhammer|knight",
   "records": {
    "maximus": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 546,
   "provisional": 743,
   "kd": {
    "maximus": 8.429,
    "monk": 65
   }
  },
  "oyoroi": {
   "title": "Takeda Shingen",
   "type": "katana|samurai",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 65,
   "provisional": 41,
   "kd": {
    "maximus": 0.347,
    "monk": 65
   }
  },
  "mail": {
   "title": "Sir Aldous",
   "type": "longsword|knightMail",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 21,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 42,
   "provisional": 46,
   "kd": {
    "maximus": 0.535,
    "monk": 12.2
   }
  },
  "naginata": {
   "title": "Tomoe Gozen",
   "type": "naginata|samurai",
   "records": {
    "maximus": {
     "wins": 21,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 159,
   "provisional": 183,
   "kd": {
    "maximus": 1.87,
    "monk": 65
   }
  },
  "odachi": {
   "title": "Makara Naotaka",
   "type": "odachi|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 180,
   "provisional": 239,
   "kd": {
    "maximus": 4.077,
    "monk": 8.429
   }
  },
  "footSpear": {
   "title": "Will Ward",
   "type": "spear|footman",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    }
   },
   "score": 15,
   "provisional": 8.1,
   "kd": {
    "maximus": 0.048,
    "monk": 5
   }
  },
  "archer": {
   "title": "Nasu no Yoichi",
   "type": "bow|samurai",
   "records": {
    "maximus": {
     "wins": 16,
     "losses": 16,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 107,
   "provisional": 102,
   "kd": {
    "maximus": 1,
    "monk": 65
   }
  },
  "teppo": {
   "title": "Suzuki Magoichi",
   "type": "matchlock|ashigaru",
   "records": {
    "maximus": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 144,
   "provisional": 383,
   "kd": {
    "maximus": 4.077,
    "monk": 65
   }
  },
  "mingGuandao": {
   "title": "Liu Ting",
   "type": "guandao|mingElite",
   "records": {
    "maximus": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 241,
   "provisional": 1024,
   "kd": {
    "maximus": 12.2,
    "monk": 65
   }
  },
  "mingThreeEyed": {
   "title": "Ma Lin",
   "type": "threeEyed|mingElite",
   "records": {
    "maximus": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 218,
   "provisional": 239,
   "kd": {
    "maximus": 2.882,
    "monk": 21
   }
  },
  "shaolin": {
   "title": "Tanzong",
   "type": "staff|monk",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 16,
     "losses": 16,
     "draws": 0
    }
   },
   "score": 2.7,
   "provisional": 2,
   "kd": {
    "maximus": 0.015,
    "monk": 1
   }
  },
  "taichi": {
   "title": "Chen Fake",
   "type": "taichi|kungfu",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 17,
     "losses": 15,
     "draws": 0
    }
   },
   "score": 1.9,
   "provisional": 2.2,
   "kd": {
    "maximus": 0.015,
    "monk": 1.129
   }
  },
  "kanabo": {
   "title": "Kojima Yatarō",
   "type": "kanabo|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 637,
   "provisional": 463,
   "kd": {
    "maximus": 5,
    "monk": 65
   }
  },
  "ironPagoda": {
   "title": "Wanyan Wuzhu",
   "type": "langyaShield|ironPagoda",
   "records": {
    "maximus": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 479,
   "provisional": 743,
   "kd": {
    "maximus": 8.429,
    "monk": 65
   }
  },
  "guanYu": {
   "title": "Guan Yu",
   "type": "guanYu|guanYu",
   "records": {
    "maximus": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 220,
   "provisional": 1584,
   "kd": {
    "maximus": 21,
    "monk": 65
   }
  },
  "hanCrossbow": {
   "title": "Li Ling",
   "type": "nu|hanSoldier",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 31,
   "provisional": 32,
   "kd": {
    "maximus": 0.347,
    "monk": 12.2
   }
  },
  "wuxia": {
   "title": "Pei Min",
   "type": "wuxia|wuxia",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 28,
     "draws": 0
    },
    "monk": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    }
   },
   "score": 18,
   "provisional": 9.2,
   "kd": {
    "maximus": 0.158,
    "monk": 3.4
   }
  },
  "kheshig": {
   "title": "Subutai",
   "type": "spear|kheshig",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 27,
     "losses": 2,
     "draws": 3
    }
   },
   "score": 21,
   "provisional": 9.9,
   "kd": {
    "maximus": 0.048,
    "monk": 7.25
   }
  },
  "esen": {
   "title": "Esen Taishi",
   "type": "maceShield|steppeHeavy",
   "records": {
    "maximus": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 280,
   "provisional": 323,
   "kd": {
    "maximus": 3.4,
    "monk": 65
   }
  },
  "mandukhai": {
   "title": "Mandukhai Khatun",
   "type": "saber|steppeMedium",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    }
   },
   "score": 15,
   "provisional": 7.1,
   "kd": {
    "maximus": 0.082,
    "monk": 3.4
   }
  },
  "steppeLancer": {
   "title": "Temür",
   "type": "spear|steppeHeavy",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 0,
     "draws": 2
    }
   },
   "score": 39,
   "provisional": 19,
   "kd": {
    "maximus": 0.119,
    "monk": 21
   }
  },
  "steppeShield": {
   "title": "Ganbold",
   "type": "saberShield|steppeMedium",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 35,
   "provisional": 14,
   "kd": {
    "maximus": 0.119,
    "monk": 8.429
   }
  },
  "steppeArcher": {
   "title": "Bayar",
   "type": "steppeBow|steppeLight",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 27,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 43,
   "provisional": 21,
   "kd": {
    "maximus": 0.2,
    "monk": 12.2
   }
  },
  "gaziAlp": {
   "title": "Turgut Alp",
   "type": "saberShield|gaziAlp",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 28,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 36,
   "provisional": 24,
   "kd": {
    "maximus": 0.158,
    "monk": 65
   }
  },
  "sipahi": {
   "title": "Davud the sipahi",
   "type": "maceShield|ottomanHeavy",
   "records": {
    "maximus": {
     "wins": 21,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 372,
   "provisional": 183,
   "kd": {
    "maximus": 1.87,
    "monk": 65
   }
  },
  "janissary": {
   "title": "Ulubatlı Hasan",
   "type": "yatagan|janissary",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    }
   },
   "score": 14,
   "provisional": 8.1,
   "kd": {
    "maximus": 0.048,
    "monk": 5
   }
  },
  "janissaryGun": {
   "title": "Mehmed Çavuş",
   "type": "matchlock|janissary",
   "records": {
    "maximus": {
     "wins": 14,
     "losses": 18,
     "draws": 0
    },
    "monk": {
     "wins": 26,
     "losses": 5,
     "draws": 1
    }
   },
   "score": 56,
   "provisional": 43,
   "kd": {
    "maximus": 0.784,
    "monk": 4.5
   }
  },
  "azapArcher": {
   "title": "Ali the azap",
   "type": "steppeBow|azap",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 28,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 44,
   "provisional": 21,
   "kd": {
    "maximus": 0.158,
    "monk": 21
   }
  },
  "azapSpear": {
   "title": "Yusuf the azap",
   "type": "spear|azap",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 27,
     "draws": 0
    },
    "monk": {
     "wins": 25,
     "losses": 2,
     "draws": 5
    }
   },
   "score": 9.8,
   "provisional": 15,
   "kd": {
    "maximus": 0.2,
    "monk": 5.6
   }
  },
  "ronin": {
   "title": "Miyamoto Musashi",
   "type": "katana|ronin",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 25,
   "provisional": 14,
   "kd": {
    "maximus": 0.119,
    "monk": 8.429
   }
  },
  "wokou": {
   "title": "Wang Zhi",
   "type": "dao|wokou",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 23,
   "provisional": 21,
   "kd": {
    "maximus": 0.119,
    "monk": 65
   }
  },
  "hidalgo": {
   "title": "Hernán Cortés",
   "type": "espada|conquistadorPlate",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 26,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 40,
   "provisional": 32,
   "kd": {
    "maximus": 0.245,
    "monk": 65
   }
  },
  "rodelero": {
   "title": "Bernal Díaz",
   "type": "espadaRodela|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    }
   },
   "score": 27,
   "provisional": 6.2,
   "kd": {
    "maximus": 0.082,
    "monk": 2.882
   }
  },
  "arquebusier": {
   "title": "Diego de Ordaz",
   "type": "matchlock|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 118,
   "provisional": 209,
   "kd": {
    "maximus": 2.882,
    "monk": 12.2
   }
  },
  "vocMusketeer": {
   "title": "Hans Pedel",
   "type": "matchlock|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 100,
   "provisional": 209,
   "kd": {
    "maximus": 2.882,
    "monk": 12.2
   }
  },
  "vocPikeman": {
   "title": "Jan de Vries",
   "type": "spear|conquistadorPlate",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 25,
     "draws": 1
    },
    "monk": {
     "wins": 31,
     "losses": 0,
     "draws": 1
    }
   },
   "score": 25,
   "provisional": 32,
   "kd": {
    "maximus": 0.269,
    "monk": 32
   }
  },
  "eagle": {
   "title": "Cuauhtémoc",
   "type": "macuahuitl|mexicaElite",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 28,
     "draws": 0
    },
    "monk": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    }
   },
   "score": 24,
   "provisional": 12,
   "kd": {
    "maximus": 0.158,
    "monk": 5
   }
  },
  "jaguar": {
   "title": "Ocelotl",
   "type": "tepoztopilli|mexicaElite",
   "records": {
    "maximus": {
     "wins": 15,
     "losses": 17,
     "draws": 0
    },
    "monk": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    }
   },
   "score": 14,
   "provisional": 51,
   "kd": {
    "maximus": 0.886,
    "monk": 5
   }
  },
  "mexica": {
   "title": "Yaotl",
   "type": "macuahuitl|mexicaWarrior",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 25,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 53,
   "provisional": 32,
   "kd": {
    "maximus": 0.294,
    "monk": 21
   }
  },
  "taekwondo": {
   "title": "Kim Min-jun",
   "type": "taekwondo|dobok",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    }
   },
   "score": 1.6,
   "provisional": 0.7,
   "kd": {
    "maximus": 0.015,
    "monk": 0.347
   }
  },
  "mingEliteGun": {
   "title": "Wu Weizhong",
   "type": "matchlock|mingElite",
   "records": {
    "maximus": {
     "wins": 20,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 194,
   "provisional": 162,
   "kd": {
    "maximus": 1.64,
    "monk": 65
   }
  },
  "mingShield": {
   "title": "Chen Bao",
   "type": "swordShield|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 25,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 90,
   "provisional": 36,
   "kd": {
    "maximus": 0.294,
    "monk": 65
   }
  },
  "mingBrigSpear": {
   "title": "Sun Qi",
   "type": "spear|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 0,
     "draws": 1
    }
   },
   "score": 21,
   "provisional": 13,
   "kd": {
    "maximus": 0.015,
    "monk": 32
   }
  },
  "mingGun": {
   "title": "Zhao Liu",
   "type": "matchlock|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 20,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 205,
   "provisional": 162,
   "kd": {
    "maximus": 1.64,
    "monk": 65
   }
  },
  "mingCrossbow": {
   "title": "Li Si",
   "type": "nu|mingGarrison",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 20,
   "provisional": 41,
   "kd": {
    "maximus": 0.347,
    "monk": 65
   }
  },
  "mingSpear": {
   "title": "Wang Er",
   "type": "spear|mingGarrison",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 27,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 9.9,
   "provisional": 21,
   "kd": {
    "maximus": 0.2,
    "monk": 12.2
   }
  },
  "mingDao": {
   "title": "Zhang San",
   "type": "dao|mingGarrison",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 25,
   "provisional": 19,
   "kd": {
    "maximus": 0.082,
    "monk": 65
   }
  },
  "arquebus": {
   "title": "Hans Brenner",
   "type": "matchlock|footman",
   "records": {
    "maximus": {
     "wins": 23,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 114,
   "provisional": 183,
   "kd": {
    "maximus": 2.474,
    "monk": 12.2
   }
  },
  "footBow": {
   "title": "Tom Fletcher",
   "type": "bow|footman",
   "records": {
    "maximus": {
     "wins": 14,
     "losses": 18,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 71,
   "provisional": 58,
   "kd": {
    "maximus": 0.784,
    "monk": 8.429
   }
  },
  "ashigaruSpear": {
   "title": "Gonbei",
   "type": "spear|ashigaru",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 0,
     "draws": 3
    }
   },
   "score": 26,
   "provisional": 17,
   "kd": {
    "maximus": 0.119,
    "monk": 15.5
   }
  },
  "ashigaruBow": {
   "title": "Sakuzaemon",
   "type": "bow|ashigaru",
   "records": {
    "maximus": {
     "wins": 21,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 92,
   "provisional": 183,
   "kd": {
    "maximus": 1.87,
    "monk": 65
   }
  },
  "hoplomachus": {
   "title": "Priscus",
   "type": "hoplomachus|hoplomachus",
   "records": {
    "maximus": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 240,
   "provisional": 383,
   "kd": {
    "maximus": 4.077,
    "monk": 65
   }
  },
  "murmillo": {
   "title": "Verus",
   "type": "murmillo|murmillo",
   "records": {
    "maximus": {
     "wins": 18,
     "losses": 14,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 68,
   "provisional": 114,
   "kd": {
    "maximus": 1.276,
    "monk": 21
   }
  },
  "secutor": {
   "title": "Flamma",
   "type": "secutor|secutor",
   "records": {
    "maximus": {
     "wins": 15,
     "losses": 17,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 112,
   "provisional": 91,
   "kd": {
    "maximus": 0.886,
    "monk": 65
   }
  },
  "thraex": {
   "title": "Spartacus",
   "type": "thraex|thraex",
   "records": {
    "maximus": {
     "wins": 17,
     "losses": 15,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 124,
   "provisional": 114,
   "kd": {
    "maximus": 1.129,
    "monk": 65
   }
  },
  "retiarius": {
   "title": "Kalendio",
   "type": "retiarius|retiarius",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 27,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 0,
     "draws": 1
    }
   },
   "score": 31,
   "provisional": 26,
   "kd": {
    "maximus": 0.2,
    "monk": 32
   }
  },
  "scissor": {
   "title": "Astacius",
   "type": "scissor|scissor",
   "records": {
    "maximus": {
     "wins": 15,
     "losses": 17,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 121,
   "provisional": 81,
   "kd": {
    "maximus": 0.886,
    "monk": 21
   }
  },
  "maximus": {
   "title": "Maximus",
   "type": "maximus|maximus",
   "records": {
    "maximus": {
     "wins": 16,
     "losses": 16,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 100,
   "provisional": 100,
   "kd": {
    "maximus": 1,
    "monk": 65
   }
  },
  "commodus": {
   "title": "Commodus",
   "type": "commodus|commodus",
   "records": {
    "maximus": {
     "wins": 13,
     "losses": 19,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 68,
   "provisional": 73,
   "kd": {
    "maximus": 0.692,
    "monk": 65
   }
  },
  "legionary": {
   "title": "Gaius Valerius Crispus",
   "type": "legionary|legionary",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 20,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 69,
   "provisional": 65,
   "kd": {
    "maximus": 0.61,
    "monk": 65
   }
  },
  "centurion": {
   "title": "Marcus Caelius",
   "type": "centurion|centurion",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 23,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 25,
   "provisional": 32,
   "kd": {
    "maximus": 0.404,
    "monk": 8.429
   }
  },
  "peasant": {
   "title": "Hob Miller",
   "type": "spear|commoner",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 28,
     "draws": 0
    },
    "monk": {
     "wins": 27,
     "losses": 4,
     "draws": 1
    }
   },
   "score": 15,
   "provisional": 13,
   "kd": {
    "maximus": 0.158,
    "monk": 5.6
   }
  },
  "pistol": {
   "title": "Sgt. Dana Cole",
   "type": "handgun|swat",
   "records": {
    "maximus": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 352,
   "provisional": 383,
   "kd": {
    "maximus": 4.077,
    "monk": 65
   }
  },
  "ladyAshford": {
   "title": "Lady Ashford",
   "type": "rapier|victorianLady",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 6,
     "losses": 26,
     "draws": 0
    }
   },
   "score": 0.6,
   "provisional": 0.5,
   "kd": {
    "maximus": 0.015,
    "monk": 0.245
   }
  },
  "lordAshford": {
   "title": "Lord Ashford",
   "type": "duelPistol|victorianGent",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 21,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 77,
   "provisional": 46,
   "kd": {
    "maximus": 0.535,
    "monk": 12.2
   }
  },
  "baton": {
   "title": "Officer Reyes",
   "type": "baton|swat",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 19,
   "provisional": 16,
   "kd": {
    "maximus": 0.048,
    "monk": 65
   }
  },
  "riot": {
   "title": "Officer Dale Burke",
   "type": "riot|riot",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 34,
   "provisional": 21,
   "kd": {
    "maximus": 0.119,
    "monk": 65
   }
  },
  "police": {
   "title": "Officer Mike Kowalski",
   "type": "handgun|police",
   "records": {
    "maximus": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 122,
   "provisional": 276,
   "kd": {
    "maximus": 3.4,
    "monk": 21
   }
  },
  "policeBaton": {
   "title": "Officer Ana Ruiz",
   "type": "baton|police",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 17,
     "losses": 15,
     "draws": 0
    }
   },
   "score": 4.6,
   "provisional": 2.2,
   "kd": {
    "maximus": 0.015,
    "monk": 1.129
   }
  },
  "swatShotgun": {
   "title": "Cpl. Marcus Hale",
   "type": "shotgun|swat",
   "records": {
    "maximus": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 1613,
   "provisional": 3267,
   "kd": {
    "maximus": 65,
    "monk": 65
   }
  },
  "specialForces": {
   "title": "SSgt. Ryan Brooks",
   "type": "rifle|specialForces",
   "records": {
    "maximus": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 557,
   "provisional": 1584,
   "kd": {
    "maximus": 65,
    "monk": 21
   }
  },
  "knife": {
   "title": "Ryo Kanda",
   "type": "knife|yakuza",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    }
   },
   "score": 13,
   "provisional": 7.1,
   "kd": {
    "maximus": 0.048,
    "monk": 4.077
   }
  },
  "boxer": {
   "title": "Marcus \"The Wall\"",
   "type": "boxing|boxing",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 25,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 32,
   "provisional": 36,
   "kd": {
    "maximus": 0.294,
    "monk": 65
   }
  },
  "kickboxer": {
   "title": "Leo Quickhands",
   "type": "kickboxing|boxing",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 9.8,
   "provisional": 14,
   "kd": {
    "maximus": 0.015,
    "monk": 65
   }
  },
  "muayThai": {
   "title": "Ana Ruiz",
   "type": "muayThai|boxing",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 15,
   "provisional": 11,
   "kd": {
    "maximus": 0.015,
    "monk": 12.2
   }
  },
  "street": {
   "title": "Vinnie Russo",
   "type": "street|casual",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 13,
     "losses": 12,
     "draws": 7
    }
   },
   "score": 5.2,
   "provisional": 2,
   "kd": {
    "maximus": 0.015,
    "monk": 1.063
   }
  },
  "sumo": {
   "title": "Takanohana",
   "type": "sumo|sumo",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 25,
     "draws": 0
    },
    "monk": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    }
   },
   "score": 21,
   "provisional": 14,
   "kd": {
    "maximus": 0.294,
    "monk": 3.4
   }
  },
  "bat": {
   "title": "Tony Marchetti",
   "type": "bat|thug",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 28,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 25,
   "provisional": 24,
   "kd": {
    "maximus": 0.158,
    "monk": 65
   }
  },
  "brawler": {
   "title": "Hank Doyle",
   "type": "clinchBrawl|mma",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 27,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 1,
     "draws": 1
    }
   },
   "score": 26,
   "provisional": 23,
   "kd": {
    "maximus": 0.2,
    "monk": 15.5
   }
  },
  "mix": {
   "title": "Kai Moana",
   "type": "mix|sports",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 14,
     "losses": 18,
     "draws": 0
    }
   },
   "score": 3.6,
   "provisional": 1.5,
   "kd": {
    "maximus": 0.015,
    "monk": 0.784
   }
  },
  "unskilled": {
   "title": "Wat Tyler",
   "type": "unskilled|commoner",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 20,
     "draws": 2
    }
   },
   "score": 1.6,
   "provisional": 1.1,
   "kd": {
    "maximus": 0.015,
    "monk": 0.535
   }
  }
 },
 "types": {
  "longsword|knight": 116,
  "joan|joan": 54,
  "crossbow|footman": 62,
  "katana|samuraiTosei": 86,
  "warhammer|knight": 546,
  "katana|samurai": 65,
  "longsword|knightMail": 42,
  "naginata|samurai": 159,
  "odachi|samuraiTosei": 180,
  "spear|footman": 15,
  "bow|samurai": 107,
  "matchlock|ashigaru": 144,
  "guandao|mingElite": 241,
  "threeEyed|mingElite": 218,
  "staff|monk": 2.7,
  "taichi|kungfu": 1.9,
  "kanabo|samuraiTosei": 637,
  "langyaShield|ironPagoda": 479,
  "guanYu|guanYu": 220,
  "nu|hanSoldier": 31,
  "wuxia|wuxia": 18,
  "spear|kheshig": 21,
  "maceShield|steppeHeavy": 280,
  "saber|steppeMedium": 15,
  "spear|steppeHeavy": 39,
  "saberShield|steppeMedium": 35,
  "steppeBow|steppeLight": 43,
  "saberShield|gaziAlp": 36,
  "maceShield|ottomanHeavy": 372,
  "yatagan|janissary": 14,
  "matchlock|janissary": 56,
  "steppeBow|azap": 44,
  "spear|azap": 9.8,
  "katana|ronin": 25,
  "dao|wokou": 23,
  "espada|conquistadorPlate": 40,
  "espadaRodela|conquistadorQuilted": 27,
  "matchlock|conquistadorQuilted": 109,
  "spear|conquistadorPlate": 25,
  "macuahuitl|mexicaElite": 24,
  "tepoztopilli|mexicaElite": 14,
  "macuahuitl|mexicaWarrior": 53,
  "taekwondo|dobok": 1.6,
  "matchlock|mingElite": 194,
  "swordShield|mingBrigandine": 90,
  "spear|mingBrigandine": 21,
  "matchlock|mingBrigandine": 205,
  "nu|mingGarrison": 20,
  "spear|mingGarrison": 9.9,
  "dao|mingGarrison": 25,
  "matchlock|footman": 114,
  "bow|footman": 71,
  "spear|ashigaru": 26,
  "bow|ashigaru": 92,
  "hoplomachus|hoplomachus": 240,
  "murmillo|murmillo": 68,
  "secutor|secutor": 112,
  "thraex|thraex": 124,
  "retiarius|retiarius": 31,
  "scissor|scissor": 121,
  "maximus|maximus": 100,
  "commodus|commodus": 68,
  "legionary|legionary": 69,
  "centurion|centurion": 25,
  "spear|commoner": 15,
  "handgun|swat": 352,
  "rapier|victorianLady": 0.6,
  "duelPistol|victorianGent": 77,
  "baton|swat": 19,
  "riot|riot": 34,
  "handgun|police": 122,
  "baton|police": 4.6,
  "shotgun|swat": 1613,
  "rifle|specialForces": 557,
  "knife|yakuza": 13,
  "boxing|boxing": 32,
  "kickboxing|boxing": 9.8,
  "muayThai|boxing": 15,
  "street|casual": 5.2,
  "sumo|sumo": 21,
  "bat|thug": 25,
  "clinchBrawl|mma": 26,
  "mix|sports": 3.6,
  "unskilled|commoner": 1.6
 },
 "cross": [
  {
   "a": "ladyAshford",
   "b": "taekwondo",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "unskilled",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "taekwondo",
   "b": "unskilled",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "shaolin",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "street",
   "wins": 8,
   "losses": 5,
   "draws": 3
  },
  {
   "a": "shaolin",
   "b": "street",
   "wins": 5,
   "losses": 9,
   "draws": 2
  },
  {
   "a": "shaolin",
   "b": "taichi",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "street",
   "b": "taichi",
   "wins": 14,
   "losses": 0,
   "draws": 2
  },
  {
   "a": "policeBaton",
   "b": "taichi",
   "wins": 13,
   "losses": 2,
   "draws": 1
  },
  {
   "a": "policeBaton",
   "b": "street",
   "wins": 2,
   "losses": 8,
   "draws": 6
  },
  {
   "a": "mandukhai",
   "b": "rodelero",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "rodelero",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "mandukhai",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "janissary",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "mandukhai",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "mandukhai",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "wuxia",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "wuxia",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "muayThai",
   "wins": 13,
   "losses": 1,
   "draws": 2
  },
  {
   "a": "muayThai",
   "b": "wuxia",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "mingBrigSpear",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "peasant",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "peasant",
   "wins": 9,
   "losses": 6,
   "draws": 1
  },
  {
   "a": "ronin",
   "b": "steppeShield",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "steppeShield",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "ronin",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "sumo",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ronin",
   "b": "sumo",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "baton",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "steppeShield",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "baton",
   "wins": 11,
   "losses": 3,
   "draws": 2
  },
  {
   "a": "ashigaruSpear",
   "b": "steppeLancer",
   "wins": 6,
   "losses": 5,
   "draws": 5
  },
  {
   "a": "ashigaruSpear",
   "b": "mingDao",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "steppeLancer",
   "wins": 4,
   "losses": 11,
   "draws": 1
  },
  {
   "a": "azapArcher",
   "b": "steppeArcher",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "steppeArcher",
   "b": "wokou",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "wokou",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "steppeArcher",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "mingSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "steppeArcher",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "riot",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "gaziAlp",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "brawler",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "gaziAlp",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "retiarius",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "retiarius",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "hidalgo",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "vocPikeman",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "vocPikeman",
   "wins": 11,
   "losses": 3,
   "draws": 2
  },
  {
   "a": "hanCrossbow",
   "b": "mexica",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "mexica",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "hanCrossbow",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "hidalgo",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "mingShield",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "tosei",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "tosei",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "tosei",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "tosei",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "oyoroi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "mail",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "lordAshford",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mail",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "jaguar",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "mail",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "legionary",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "legionary",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "legionary",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "joan",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "scissor",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "scissor",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "scissor",
   "b": "secutor",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "secutor",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "maximus",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "secutor",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "thraex",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "murmillo",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "thraex",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "plate",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "plate",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "mingGun",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "sipahi",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "naginata",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "naginata",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "sipahi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "crossbowman",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "vocMusketeer",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "vocMusketeer",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "odachi",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "odachi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "mingThreeEyed",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "police",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "police",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "police",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "teppo",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "teppo",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "teppo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "pistol",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "teppo",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "kanabo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "ironPagoda",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "mingGuandao",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mingGuandao",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "mingGuandao",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "swatShotgun",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "specialForces",
   "b": "swatShotgun",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "plate",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "plate",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "plate",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "plate",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "joan",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "shaolin",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "joan",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "joan",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "legionary",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "mexica",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "murmillo",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "mandukhai",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "tosei",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "thraex",
   "b": "tosei",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "tosei",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "tosei",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "tosei",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "hammer",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "wuxia",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "oyoroi",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "oyoroi",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "oyoroi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "mingGuandao",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "tosei",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "ronin",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "mail",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "naginata",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "vocPikeman",
   "wins": 12,
   "losses": 3,
   "draws": 1
  },
  {
   "a": "mingSpear",
   "b": "naginata",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "pistol",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "odachi",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "retiarius",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "odachi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mexica",
   "b": "odachi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "steppeLancer",
   "wins": 5,
   "losses": 5,
   "draws": 6
  },
  {
   "a": "footSpear",
   "b": "gaziAlp",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "mingCrossbow",
   "wins": 3,
   "losses": 12,
   "draws": 1
  },
  {
   "a": "footSpear",
   "b": "murmillo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "jaguar",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "esen",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "mexica",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "shaolin",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "teppo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "teppo",
   "b": "wuxia",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "teppo",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "teppo",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "rodelero",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "ronin",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "mingGuandao",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "steppeLancer",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "mingThreeEyed",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "mingThreeEyed",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "mingThreeEyed",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "murmillo",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "shaolin",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "shaolin",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "shaolin",
   "b": "unskilled",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "shaolin",
   "b": "vocPikeman",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "taichi",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "taichi",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "mingGun",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "murmillo",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "kanabo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "kanabo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "lordAshford",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "specialForces",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "pistol",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "ironPagoda",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "guanYu",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "steppeArcher",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "sipahi",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "peasant",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "taekwondo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "peasant",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "mingGuandao",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "lordAshford",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "wuxia",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "wuxia",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "wuxia",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "wuxia",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "unskilled",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "kickboxer",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "mingGun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "steppeShield",
   "wins": 8,
   "losses": 7,
   "draws": 1
  },
  {
   "a": "esen",
   "b": "wokou",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "muayThai",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "mingCrossbow",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "riot",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "sipahi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "mingCrossbow",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "secutor",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "teppo",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "steppeLancer",
   "wins": 11,
   "losses": 3,
   "draws": 2
  },
  {
   "a": "brawler",
   "b": "steppeLancer",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "steppeLancer",
   "wins": 4,
   "losses": 11,
   "draws": 1
  },
  {
   "a": "steppeLancer",
   "b": "teppo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "steppeShield",
   "wins": 13,
   "losses": 2,
   "draws": 1
  },
  {
   "a": "mandukhai",
   "b": "steppeShield",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "wuxia",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "steppeShield",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "steppeArcher",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "scissor",
   "b": "steppeArcher",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "steppeArcher",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "steppeArcher",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "mingBrigSpear",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "gaziAlp",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "gaziAlp",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "legionary",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "sumo",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "sipahi",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "specialForces",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "vocMusketeer",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "janissary",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "retiarius",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "janissary",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "mingGuandao",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "mingDao",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "murmillo",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "swatShotgun",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "thraex",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "mingShield",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "vocMusketeer",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "oyoroi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "swatShotgun",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "janissary",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "steppeArcher",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "kheshig",
   "wins": 2,
   "losses": 10,
   "draws": 4
  },
  {
   "a": "azapArcher",
   "b": "ronin",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "ronin",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "ronin",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "ronin",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "wokou",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "thraex",
   "b": "wokou",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "wokou",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "wokou",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "hidalgo",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "mix",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "mingGuandao",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "mingShield",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "rodelero",
   "b": "ronin",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "rodelero",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "rodelero",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "rodelero",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "ashigaruBow",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "gaziAlp",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "knife",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "vocMusketeer",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "vocMusketeer",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "vocMusketeer",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "vocMusketeer",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "vocPikeman",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "police",
   "b": "vocPikeman",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "vocPikeman",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "vocPikeman",
   "wins": 5,
   "losses": 10,
   "draws": 1
  },
  {
   "a": "eagle",
   "b": "secutor",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "specialForces",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "teppo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "footBow",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "retiarius",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "steppeLancer",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "mingCrossbow",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "kheshig",
   "wins": 2,
   "losses": 13,
   "draws": 1
  },
  {
   "a": "mexica",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "mexica",
   "wins": 8,
   "losses": 7,
   "draws": 1
  },
  {
   "a": "mexica",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "mexica",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "taekwondo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "taekwondo",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "taekwondo",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mexica",
   "b": "taekwondo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "ronin",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "mingEliteGun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "mingEliteGun",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mingEliteGun",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "mingShield",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mexica",
   "b": "mingShield",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "mingThreeEyed",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "mingShield",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "mix",
   "wins": 13,
   "losses": 0,
   "draws": 3
  },
  {
   "a": "mingBrigSpear",
   "b": "tosei",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mingBrigSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "mingBrigSpear",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "mingGun",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "teppo",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "mingGun",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "secutor",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "mingGuandao",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "mix",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "murmillo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "scissor",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "mingSpear",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "mingSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "mingSpear",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "mingSpear",
   "wins": 7,
   "losses": 4,
   "draws": 5
  },
  {
   "a": "esen",
   "b": "mingDao",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mingDao",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "mingShield",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "mingDao",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "janissary",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "knife",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "kanabo",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "steppeShield",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "footBow",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "footBow",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "riot",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "sipahi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "ashigaruSpear",
   "wins": 13,
   "losses": 2,
   "draws": 1
  },
  {
   "a": "ashigaruSpear",
   "b": "azapSpear",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "mix",
   "wins": 13,
   "losses": 0,
   "draws": 3
  },
  {
   "a": "archer",
   "b": "ashigaruSpear",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "wuxia",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "brawler",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "footSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "ashigaruBow",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "hoplomachus",
   "wins": 7,
   "losses": 8,
   "draws": 1
  },
  {
   "a": "bat",
   "b": "hoplomachus",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "hoplomachus",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "janissaryGun",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "murmillo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "murmillo",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "murmillo",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "murmillo",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "secutor",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "secutor",
   "wins": 10,
   "losses": 5,
   "draws": 1
  },
  {
   "a": "knife",
   "b": "secutor",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "secutor",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "thraex",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "thraex",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "thraex",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "thraex",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "retiarius",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "police",
   "b": "retiarius",
   "wins": 10,
   "losses": 5,
   "draws": 1
  },
  {
   "a": "retiarius",
   "b": "secutor",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "retiarius",
   "wins": 6,
   "losses": 9,
   "draws": 1
  },
  {
   "a": "police",
   "b": "scissor",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "scissor",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "scissor",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "scissor",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "maximus",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "mingCrossbow",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "sumo",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "mingBrigSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "hoplomachus",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "mingGun",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "commodus",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "ronin",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "legionary",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "legionary",
   "wins": 4,
   "losses": 11,
   "draws": 1
  },
  {
   "a": "legionary",
   "b": "plate",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "mingShield",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "ronin",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "naginata",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "mingThreeEyed",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "retiarius",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "peasant",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "peasant",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "plate",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "pistol",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "pistol",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "pistol",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "pistol",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "oyoroi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "ladyAshford",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "ladyAshford",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "taichi",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "rodelero",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "lordAshford",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "maximus",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mingBrigSpear",
   "wins": 12,
   "losses": 3,
   "draws": 1
  },
  {
   "a": "baton",
   "b": "footSpear",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "mexica",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "hanCrossbow",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "taekwondo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "scissor",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "teppo",
   "wins": 0,
   "losses": 15,
   "draws": 1
  },
  {
   "a": "legionary",
   "b": "riot",
   "wins": 12,
   "losses": 3,
   "draws": 1
  },
  {
   "a": "riot",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "police",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "police",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "police",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "police",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "policeBaton",
   "wins": 7,
   "losses": 7,
   "draws": 2
  },
  {
   "a": "ironPagoda",
   "b": "policeBaton",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "policeBaton",
   "b": "scissor",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "policeBaton",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "ronin",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "specialForces",
   "b": "taekwondo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "odachi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "knife",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "knife",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "esen",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "mingBrigSpear",
   "wins": 5,
   "losses": 9,
   "draws": 2
  },
  {
   "a": "boxer",
   "b": "eagle",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "commodus",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mail",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "kickboxer",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "kickboxer",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "kickboxer",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "police",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "muayThai",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "muayThai",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "muayThai",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "street",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "street",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "street",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "street",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "sumo",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "sumo",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "sumo",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "sumo",
   "wins": 6,
   "losses": 7,
   "draws": 3
  },
  {
   "a": "bat",
   "b": "janissary",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "centurion",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "kickboxer",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "mingShield",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "rodelero",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "legionary",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "steppeArcher",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "shaolin",
   "wins": 15,
   "losses": 0,
   "draws": 1
  },
  {
   "a": "mix",
   "b": "pistol",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "mix",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "mix",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "thraex",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "unskilled",
   "b": "vocMusketeer",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "specialForces",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  }
 ]
};
