// GENERATED by tools/ratings.js (16 bouts a corner against each reference, 8 against each of two nearest-rated and 4 drawn at random) — do not edit by hand; re-run the tool.
// Score = strength fitted to all those bouts at once (Bradley-Terry), Maximus held at 100: ∝ inferred K/D.
export const RATINGS = {
 "references": [
  "maximus",
  "monk"
 ],
 "bouts": 16,
 "crossBouts": 8,
 "characters": {
  "ironPagoda": {
   "title": "Wanyan Wuzhu",
   "type": "langyaShield|ironPagoda",
   "records": {
    "maximus": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 678,
   "provisional": 432,
   "kd": {
    "maximus": 6.333,
    "monk": 12.2
   }
  },
  "plate": {
   "title": "Sir Edric",
   "type": "longsword|knight",
   "records": {
    "maximus": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 339,
   "provisional": 317,
   "kd": {
    "maximus": 6.333,
    "monk": 6.333
   }
  },
  "hammer": {
   "title": "Gunnar Holt",
   "type": "warhammer|knight",
   "records": {
    "maximus": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 974,
   "provisional": 519,
   "kd": {
    "maximus": 6.333,
    "monk": 21
   }
  },
  "kanabo": {
   "title": "Kojima Yatarō",
   "type": "kanabo|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 776,
   "provisional": 317,
   "kd": {
    "maximus": 6.333,
    "monk": 6.333
   }
  },
  "mingThreeEyed": {
   "title": "Ma Lin",
   "type": "threeEyed|mingElite",
   "records": {
    "maximus": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 921,
   "provisional": 823,
   "kd": {
    "maximus": 8.429,
    "monk": 65
   }
  },
  "mingGuandao": {
   "title": "Liu Ting",
   "type": "guandao|mingElite",
   "records": {
    "maximus": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 376,
   "provisional": 823,
   "kd": {
    "maximus": 8.429,
    "monk": 65
   }
  },
  "odachi": {
   "title": "Makara Naotaka",
   "type": "odachi|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 380,
   "provisional": 276,
   "kd": {
    "maximus": 5,
    "monk": 6.333
   }
  },
  "mingEliteGun": {
   "title": "Wu Weizhong",
   "type": "matchlock|mingElite",
   "records": {
    "maximus": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 358,
   "provisional": 276,
   "kd": {
    "maximus": 2.882,
    "monk": 21
   }
  },
  "joan": {
   "title": "Joan of Arc",
   "type": "joan|joan",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 22,
     "draws": 0
    },
    "monk": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    }
   },
   "score": 15,
   "provisional": 10,
   "kd": {
    "maximus": 0.467,
    "monk": 0.347
   }
  },
  "tosei": {
   "title": "Date Masamune",
   "type": "katana|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 20,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 258,
   "provisional": 156,
   "kd": {
    "maximus": 1.64,
    "monk": 12.2
   }
  },
  "guanYu": {
   "title": "Guan Yu",
   "type": "guanYu|guanYu",
   "records": {
    "maximus": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 337,
   "provisional": 317,
   "kd": {
    "maximus": 5,
    "monk": 8.429
   }
  },
  "naginata": {
   "title": "Tomoe Gozen",
   "type": "naginata|samurai",
   "records": {
    "maximus": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 351,
   "provisional": 519,
   "kd": {
    "maximus": 6.333,
    "monk": 21
   }
  },
  "archer": {
   "title": "Nasu no Yoichi",
   "type": "bow|samurai",
   "records": {
    "maximus": {
     "wins": 18,
     "losses": 14,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 236,
   "provisional": 141,
   "kd": {
    "maximus": 1.276,
    "monk": 21
   }
  },
  "mail": {
   "title": "Sir Aldous",
   "type": "longsword|knightMail",
   "records": {
    "maximus": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 181,
   "provisional": 367,
   "kd": {
    "maximus": 4.077,
    "monk": 21
   }
  },
  "oyoroi": {
   "title": "Takeda Shingen",
   "type": "katana|samurai",
   "records": {
    "maximus": {
     "wins": 17,
     "losses": 15,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 97,
   "provisional": 106,
   "kd": {
    "maximus": 1.129,
    "monk": 8.429
   }
  },
  "scissor": {
   "title": "Astacius",
   "type": "scissor|scissor",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 20,
     "draws": 0
    },
    "monk": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    }
   },
   "score": 98,
   "provisional": 45,
   "kd": {
    "maximus": 0.61,
    "monk": 2.882
   }
  },
  "kheshig": {
   "title": "Subutai",
   "type": "spear|kheshig",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 23,
     "draws": 0
    },
    "monk": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    }
   },
   "score": 58,
   "provisional": 42,
   "kd": {
    "maximus": 0.404,
    "monk": 4.077
   }
  },
  "specialForces": {
   "title": "SSgt. Ryan Brooks",
   "type": "rifle|specialForces",
   "records": {
    "maximus": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 3273,
   "provisional": 3562,
   "kd": {
    "maximus": 65,
    "monk": 65
   }
  },
  "esen": {
   "title": "Esen Taishi",
   "type": "maceShield|steppeHeavy",
   "records": {
    "maximus": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 1715,
   "provisional": 1736,
   "kd": {
    "maximus": 65,
    "monk": 21
   }
  },
  "secutor": {
   "title": "Flamma",
   "type": "secutor|secutor",
   "records": {
    "maximus": {
     "wins": 21,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 151,
   "provisional": 141,
   "kd": {
    "maximus": 1.87,
    "monk": 6.333
   }
  },
  "murmillo": {
   "title": "Verus",
   "type": "murmillo|murmillo",
   "records": {
    "maximus": {
     "wins": 20,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 120,
   "provisional": 173,
   "kd": {
    "maximus": 1.64,
    "monk": 21
   }
  },
  "steppeLancer": {
   "title": "Temür",
   "type": "spear|steppeHeavy",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 27,
     "draws": 0
    },
    "monk": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 74,
   "provisional": 36,
   "kd": {
    "maximus": 0.2,
    "monk": 6.333
   }
  },
  "hoplomachus": {
   "title": "Priscus",
   "type": "hoplomachus|hoplomachus",
   "records": {
    "maximus": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 171,
   "provisional": 216,
   "kd": {
    "maximus": 3.4,
    "monk": 6.333
   }
  },
  "sipahi": {
   "title": "Davud the sipahi",
   "type": "maceShield|ottomanHeavy",
   "records": {
    "maximus": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 1671,
   "provisional": 3562,
   "kd": {
    "maximus": 65,
    "monk": 65
   }
  },
  "thraex": {
   "title": "Spartacus",
   "type": "thraex|thraex",
   "records": {
    "maximus": {
     "wins": 23,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 150,
   "provisional": 216,
   "kd": {
    "maximus": 2.474,
    "monk": 12.2
   }
  },
  "vocPikeman": {
   "title": "Jan de Vries",
   "type": "spear|conquistadorPlate",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 20,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 117,
   "provisional": 75,
   "kd": {
    "maximus": 0.61,
    "monk": 12.2
   }
  },
  "hidalgo": {
   "title": "Hernán Cortés",
   "type": "espada|conquistadorPlate",
   "records": {
    "maximus": {
     "wins": 22,
     "losses": 10,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 215,
   "provisional": 193,
   "kd": {
    "maximus": 2.143,
    "monk": 12.2
   }
  },
  "centurion": {
   "title": "Marcus Caelius",
   "type": "centurion|centurion",
   "records": {
    "maximus": {
     "wins": 21,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    }
   },
   "score": 108,
   "provisional": 106,
   "kd": {
    "maximus": 1.87,
    "monk": 3.4
   }
  },
  "legionary": {
   "title": "Gaius Valerius Crispus",
   "type": "legionary|legionary",
   "records": {
    "maximus": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 321,
   "provisional": 1127,
   "kd": {
    "maximus": 21,
    "monk": 21
   }
  },
  "gaziAlp": {
   "title": "Turgut Alp",
   "type": "saberShield|gaziAlp",
   "records": {
    "maximus": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 290,
   "provisional": 519,
   "kd": {
    "maximus": 6.333,
    "monk": 21
   }
  },
  "mingGun": {
   "title": "Zhao Liu",
   "type": "matchlock|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 22,
     "losses": 10,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 96,
   "provisional": 216,
   "kd": {
    "maximus": 2.143,
    "monk": 21
   }
  },
  "mingShield": {
   "title": "Chen Bao",
   "type": "swordShield|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 491,
   "provisional": 276,
   "kd": {
    "maximus": 2.882,
    "monk": 21
   }
  },
  "mingBrigSpear": {
   "title": "Sun Qi",
   "type": "spear|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 38,
   "provisional": 39,
   "kd": {
    "maximus": 0.082,
    "monk": 65
   }
  },
  "crossbowman": {
   "title": "Ottone Doria",
   "type": "crossbow|footman",
   "records": {
    "maximus": {
     "wins": 21,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 132,
   "provisional": 193,
   "kd": {
    "maximus": 1.87,
    "monk": 21
   }
  },
  "arquebus": {
   "title": "Hans Brenner",
   "type": "matchlock|footman",
   "records": {
    "maximus": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 295,
   "provisional": 1127,
   "kd": {
    "maximus": 12.2,
    "monk": 65
   }
  },
  "footBow": {
   "title": "Tom Fletcher",
   "type": "bow|footman",
   "records": {
    "maximus": {
     "wins": 20,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 201,
   "provisional": 173,
   "kd": {
    "maximus": 1.64,
    "monk": 21
   }
  },
  "footSpear": {
   "title": "Will Ward",
   "type": "spear|footman",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    },
    "monk": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 65,
   "provisional": 45,
   "kd": {
    "maximus": 0.347,
    "monk": 6.333
   }
  },
  "swatShotgun": {
   "title": "Cpl. Marcus Hale",
   "type": "shotgun|swat",
   "records": {
    "maximus": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 1510,
   "provisional": 823,
   "kd": {
    "maximus": 8.429,
    "monk": 65
   }
  },
  "pistol": {
   "title": "Sgt. Dana Cole",
   "type": "handgun|swat",
   "records": {
    "maximus": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 0,
     "draws": 2
    }
   },
   "score": 424,
   "provisional": 317,
   "kd": {
    "maximus": 3.4,
    "monk": 21
   }
  },
  "teppo": {
   "title": "Suzuki Magoichi",
   "type": "matchlock|ashigaru",
   "records": {
    "maximus": {
     "wins": 24,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 154,
   "provisional": 317,
   "kd": {
    "maximus": 2.882,
    "monk": 65
   }
  },
  "ashigaruBow": {
   "title": "Sakuzaemon",
   "type": "bow|ashigaru",
   "records": {
    "maximus": {
     "wins": 17,
     "losses": 15,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 133,
   "provisional": 128,
   "kd": {
    "maximus": 1.129,
    "monk": 21
   }
  },
  "baton": {
   "title": "Officer Reyes",
   "type": "baton|swat",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 18,
     "losses": 1,
     "draws": 13
    }
   },
   "score": 22,
   "provisional": 19,
   "kd": {
    "maximus": 0.048,
    "monk": 3.125
   }
  },
  "ashigaruSpear": {
   "title": "Gonbei",
   "type": "yari|ashigaru",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 24,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 55,
   "provisional": 49,
   "kd": {
    "maximus": 0.347,
    "monk": 8.429
   }
  },
  "riot": {
   "title": "Officer Dale Burke",
   "type": "riot|riot",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 21,
     "draws": 1
    },
    "monk": {
     "wins": 23,
     "losses": 5,
     "draws": 4
    }
   },
   "score": 38,
   "provisional": 44,
   "kd": {
    "maximus": 0.5,
    "monk": 3.4
   }
  },
  "hanCrossbow": {
   "title": "Li Ling",
   "type": "nu|hanSoldier",
   "records": {
    "maximus": {
     "wins": 18,
     "losses": 14,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 85,
   "provisional": 128,
   "kd": {
    "maximus": 1.276,
    "monk": 12.2
   }
  },
  "steppeShield": {
   "title": "Ganbold",
   "type": "saberShield|steppeMedium",
   "records": {
    "maximus": {
     "wins": 23,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 358,
   "provisional": 216,
   "kd": {
    "maximus": 2.474,
    "monk": 12.2
   }
  },
  "mandukhai": {
   "title": "Mandukhai Khatun",
   "type": "saber|steppeMedium",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 28,
     "draws": 0
    },
    "monk": {
     "wins": 22,
     "losses": 10,
     "draws": 0
    }
   },
   "score": 37,
   "provisional": 20,
   "kd": {
    "maximus": 0.158,
    "monk": 2.143
   }
  },
  "arquebusier": {
   "title": "Diego de Ordaz",
   "type": "matchlock|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 518,
   "provisional": 519,
   "kd": {
    "maximus": 5,
    "monk": 65
   }
  },
  "vocMusketeer": {
   "title": "Hans Pedel",
   "type": "matchlock|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 493,
   "provisional": 519,
   "kd": {
    "maximus": 5,
    "monk": 65
   }
  },
  "rodelero": {
   "title": "Bernal Díaz",
   "type": "espadaRodela|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 278,
   "provisional": 317,
   "kd": {
    "maximus": 3.4,
    "monk": 21
   }
  },
  "maximus": {
   "title": "Maximus",
   "type": "maximus|maximus",
   "records": {
    "maximus": {
     "wins": 16,
     "losses": 16,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 100,
   "provisional": 100,
   "kd": {
    "maximus": 1,
    "monk": 65
   }
  },
  "eagle": {
   "title": "Cuauhtémoc",
   "type": "macuahuitl|mexicaElite",
   "records": {
    "maximus": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 292,
   "provisional": 1127,
   "kd": {
    "maximus": 12.2,
    "monk": 65
   }
  },
  "jaguar": {
   "title": "Ocelotl",
   "type": "tepoztopilli|mexicaElite",
   "records": {
    "maximus": {
     "wins": 25,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 212,
   "provisional": 317,
   "kd": {
    "maximus": 3.4,
    "monk": 21
   }
  },
  "police": {
   "title": "Officer Mike Kowalski",
   "type": "handgun|police",
   "records": {
    "maximus": {
     "wins": 20,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 27,
     "losses": 5,
     "draws": 0
    }
   },
   "score": 153,
   "provisional": 117,
   "kd": {
    "maximus": 1.64,
    "monk": 5
   }
  },
  "ladyAshford": {
   "title": "Lady Ashford",
   "type": "revolver|victorianLady",
   "records": {
    "maximus": {
     "wins": 28,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 409,
   "provisional": 519,
   "kd": {
    "maximus": 6.333,
    "monk": 21
   }
  },
  "steppeArcher": {
   "title": "Bayar",
   "type": "steppeBow|steppeLight",
   "records": {
    "maximus": {
     "wins": 18,
     "losses": 14,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 114,
   "provisional": 141,
   "kd": {
    "maximus": 1.276,
    "monk": 21
   }
  },
  "janissaryGun": {
   "title": "Mehmed Çavuş",
   "type": "matchlock|janissary",
   "records": {
    "maximus": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 218,
   "provisional": 367,
   "kd": {
    "maximus": 4.077,
    "monk": 21
   }
  },
  "commodus": {
   "title": "Commodus",
   "type": "commodus|commodus",
   "records": {
    "maximus": {
     "wins": 13,
     "losses": 19,
     "draws": 0
    },
    "monk": {
     "wins": 31,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 123,
   "provisional": 89,
   "kd": {
    "maximus": 0.692,
    "monk": 21
   }
  },
  "mexica": {
   "title": "Yaotl",
   "type": "macuahuitl|mexicaWarrior",
   "records": {
    "maximus": {
     "wins": 30,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 234,
   "provisional": 1127,
   "kd": {
    "maximus": 12.2,
    "monk": 65
   }
  },
  "boxer": {
   "title": "Marcus \"The Wall\"",
   "type": "boxing|boxing",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 25,
     "draws": 0
    },
    "monk": {
     "wins": 24,
     "losses": 6,
     "draws": 2
    }
   },
   "score": 33,
   "provisional": 33,
   "kd": {
    "maximus": 0.294,
    "monk": 3.4
   }
  },
  "azapArcher": {
   "title": "Ali the azap",
   "type": "steppeBow|azap",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 26,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 46,
   "provisional": 42,
   "kd": {
    "maximus": 0.245,
    "monk": 8.429
   }
  },
  "retiarius": {
   "title": "Kalendio",
   "type": "retiarius|retiarius",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 23,
     "draws": 0
    },
    "monk": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    }
   },
   "score": 29,
   "provisional": 42,
   "kd": {
    "maximus": 0.404,
    "monk": 4.077
   }
  },
  "brawler": {
   "title": "Hank Doyle",
   "type": "clinchBrawl|mma",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 26,
     "draws": 0
    },
    "monk": {
     "wins": 19,
     "losses": 10,
     "draws": 3
    }
   },
   "score": 22,
   "provisional": 21,
   "kd": {
    "maximus": 0.245,
    "monk": 1.75
   }
  },
  "bat": {
   "title": "Tony Marchetti",
   "type": "bat|thug",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 21,
     "draws": 1
    }
   },
   "score": 10,
   "provisional": 6.5,
   "kd": {
    "maximus": 0.119,
    "monk": 0.5
   }
  },
  "sumo": {
   "title": "Takanohana",
   "type": "sumo|sumo",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 3,
     "losses": 26,
     "draws": 3
    }
   },
   "score": 13,
   "provisional": 2.7,
   "kd": {
    "maximus": 0.082,
    "monk": 0.179
   }
  },
  "azapSpear": {
   "title": "Yusuf the azap",
   "type": "spear|azap",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 21,
     "draws": 0
    },
    "monk": {
     "wins": 26,
     "losses": 6,
     "draws": 0
    }
   },
   "score": 40,
   "provisional": 49,
   "kd": {
    "maximus": 0.535,
    "monk": 4.077
   }
  },
  "wokou": {
   "title": "Wang Zhi",
   "type": "dao|wokou",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 22,
     "losses": 10,
     "draws": 0
    }
   },
   "score": 21,
   "provisional": 18,
   "kd": {
    "maximus": 0.119,
    "monk": 2.143
   }
  },
  "mingDao": {
   "title": "Zhang San",
   "type": "dao|mingGarrison",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 18,
     "losses": 14,
     "draws": 0
    }
   },
   "score": 18,
   "provisional": 12,
   "kd": {
    "maximus": 0.082,
    "monk": 1.276
   }
  },
  "knife": {
   "title": "Ryo Kanda",
   "type": "knife|yakuza",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 22,
     "draws": 0
    }
   },
   "score": 9.7,
   "provisional": 5.6,
   "kd": {
    "maximus": 0.082,
    "monk": 0.467
   }
  },
  "kickboxer": {
   "title": "Leo Quickhands",
   "type": "kickboxing|boxing",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 26,
     "losses": 5,
     "draws": 1
    }
   },
   "score": 11,
   "provisional": 21,
   "kd": {
    "maximus": 0.015,
    "monk": 4.5
   }
  },
  "muayThai": {
   "title": "Ana Ruiz",
   "type": "muayThai|boxing",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 18,
     "losses": 14,
     "draws": 0
    }
   },
   "score": 10,
   "provisional": 11,
   "kd": {
    "maximus": 0.048,
    "monk": 1.276
   }
  },
  "ronin": {
   "title": "Miyamoto Musashi",
   "type": "katana|ronin",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 20,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 90,
   "provisional": 89,
   "kd": {
    "maximus": 0.61,
    "monk": 65
   }
  },
  "mingSpear": {
   "title": "Wang Er",
   "type": "spear|mingGarrison",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 30,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 20,
     "draws": 1
    }
   },
   "score": 7,
   "provisional": 6.5,
   "kd": {
    "maximus": 0.082,
    "monk": 0.571
   }
  },
  "janissary": {
   "title": "Ulubatlı Hasan",
   "type": "yatagan|janissary",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 20,
     "draws": 0
    },
    "monk": {
     "wins": 29,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 76,
   "provisional": 69,
   "kd": {
    "maximus": 0.61,
    "monk": 8.429
   }
  },
  "lordAshford": {
   "title": "Lord Ashford",
   "type": "rapier|victorianGent",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 25,
     "draws": 0
    },
    "monk": {
     "wins": 7,
     "losses": 25,
     "draws": 0
    }
   },
   "score": 14,
   "provisional": 6.9,
   "kd": {
    "maximus": 0.294,
    "monk": 0.294
   }
  },
  "wuxia": {
   "title": "Pei Min",
   "type": "wuxia|wuxia",
   "records": {
    "maximus": {
     "wins": 23,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 32,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 133,
   "provisional": 276,
   "kd": {
    "maximus": 2.474,
    "monk": 65
   }
  },
  "street": {
   "title": "Vinnie Russo",
   "type": "street|casual",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 1,
     "losses": 27,
     "draws": 4
    }
   },
   "score": 3.1,
   "provisional": 1.3,
   "kd": {
    "maximus": 0.015,
    "monk": 0.119
   }
  },
  "mingCrossbow": {
   "title": "Li Si",
   "type": "nu|mingGarrison",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 6,
     "losses": 23,
     "draws": 3
    }
   },
   "score": 2.8,
   "provisional": 3.1,
   "kd": {
    "maximus": 0.015,
    "monk": 0.32
   }
  },
  "mix": {
   "title": "Kai Moana",
   "type": "mix|sports",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 31,
     "draws": 0
    },
    "monk": {
     "wins": 22,
     "losses": 6,
     "draws": 4
    }
   },
   "score": 10,
   "provisional": 18,
   "kd": {
    "maximus": 0.048,
    "monk": 2.882
   }
  },
  "policeBaton": {
   "title": "Officer Ana Ruiz",
   "type": "baton|police",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    }
   },
   "score": 2.6,
   "provisional": 0.3,
   "kd": {
    "maximus": 0.015,
    "monk": 0.015
   }
  },
  "unskilled": {
   "title": "Wat Tyler",
   "type": "unskilled|commoner",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 0,
     "losses": 30,
     "draws": 2
    }
   },
   "score": 0.7,
   "provisional": 0.6,
   "kd": {
    "maximus": 0.015,
    "monk": 0.048
   }
  },
  "taekwondo": {
   "title": "Kim Min-jun",
   "type": "taekwondo|dobok",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 23,
     "losses": 5,
     "draws": 4
    }
   },
   "score": 16,
   "provisional": 18,
   "kd": {
    "maximus": 0.015,
    "monk": 3.4
   }
  },
  "taichi": {
   "title": "Chen Fake",
   "type": "taichi|kungfu",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 14,
     "losses": 16,
     "draws": 2
    }
   },
   "score": 11,
   "provisional": 7.6,
   "kd": {
    "maximus": 0.015,
    "monk": 0.886
   }
  },
  "lorarius": {
   "title": "Felix the lorarius",
   "type": "whip|lorarius",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 8,
     "draws": 14
    }
   },
   "score": 6.6,
   "provisional": 9.2,
   "kd": {
    "maximus": 0.015,
    "monk": 1.129
   }
  },
  "shaolin": {
   "title": "Tanzong",
   "type": "staff|monk",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 32,
     "draws": 0
    },
    "monk": {
     "wins": 13,
     "losses": 13,
     "draws": 6
    }
   },
   "score": 12,
   "provisional": 11,
   "kd": {
    "maximus": 0.015,
    "monk": 1
   }
  },
  "peasant": {
   "title": "Hob Miller",
   "type": "pitchfork|commoner",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 29,
     "draws": 0
    },
    "monk": {
     "wins": 9,
     "losses": 18,
     "draws": 5
    }
   },
   "score": 13,
   "provisional": 7.2,
   "kd": {
    "maximus": 0.119,
    "monk": 0.571
   }
  }
 },
 "types": {
  "langyaShield|ironPagoda": 678,
  "longsword|knight": 339,
  "warhammer|knight": 974,
  "kanabo|samuraiTosei": 776,
  "threeEyed|mingElite": 921,
  "guandao|mingElite": 376,
  "odachi|samuraiTosei": 380,
  "matchlock|mingElite": 358,
  "joan|joan": 15,
  "katana|samuraiTosei": 258,
  "guanYu|guanYu": 337,
  "naginata|samurai": 351,
  "bow|samurai": 236,
  "longsword|knightMail": 181,
  "katana|samurai": 97,
  "scissor|scissor": 98,
  "spear|kheshig": 58,
  "rifle|specialForces": 3273,
  "maceShield|steppeHeavy": 1715,
  "secutor|secutor": 151,
  "murmillo|murmillo": 120,
  "spear|steppeHeavy": 74,
  "hoplomachus|hoplomachus": 171,
  "maceShield|ottomanHeavy": 1671,
  "thraex|thraex": 150,
  "spear|conquistadorPlate": 117,
  "espada|conquistadorPlate": 215,
  "centurion|centurion": 108,
  "legionary|legionary": 321,
  "saberShield|gaziAlp": 290,
  "matchlock|mingBrigandine": 96,
  "swordShield|mingBrigandine": 491,
  "spear|mingBrigandine": 38,
  "crossbow|footman": 132,
  "matchlock|footman": 295,
  "bow|footman": 201,
  "spear|footman": 65,
  "shotgun|swat": 1510,
  "handgun|swat": 424,
  "matchlock|ashigaru": 154,
  "bow|ashigaru": 133,
  "baton|swat": 22,
  "yari|ashigaru": 55,
  "riot|riot": 38,
  "nu|hanSoldier": 85,
  "saberShield|steppeMedium": 358,
  "saber|steppeMedium": 37,
  "matchlock|conquistadorQuilted": 505,
  "espadaRodela|conquistadorQuilted": 278,
  "maximus|maximus": 100,
  "macuahuitl|mexicaElite": 292,
  "tepoztopilli|mexicaElite": 212,
  "handgun|police": 153,
  "revolver|victorianLady": 409,
  "steppeBow|steppeLight": 114,
  "matchlock|janissary": 218,
  "commodus|commodus": 123,
  "macuahuitl|mexicaWarrior": 234,
  "boxing|boxing": 33,
  "steppeBow|azap": 46,
  "retiarius|retiarius": 29,
  "clinchBrawl|mma": 22,
  "bat|thug": 10,
  "sumo|sumo": 13,
  "spear|azap": 40,
  "dao|wokou": 21,
  "dao|mingGarrison": 18,
  "knife|yakuza": 9.7,
  "kickboxing|boxing": 11,
  "muayThai|boxing": 10,
  "katana|ronin": 90,
  "spear|mingGarrison": 7,
  "yatagan|janissary": 76,
  "rapier|victorianGent": 14,
  "wuxia|wuxia": 133,
  "street|casual": 3.1,
  "nu|mingGarrison": 2.8,
  "mix|sports": 10,
  "baton|police": 2.6,
  "unskilled|commoner": 0.7,
  "taekwondo|dobok": 16,
  "taichi|kungfu": 11,
  "whip|lorarius": 6.6,
  "staff|monk": 12,
  "pitchfork|commoner": 13
 },
 "cross": [
  {
   "a": "policeBaton",
   "b": "unskilled",
   "wins": 12,
   "losses": 2,
   "draws": 2
  },
  {
   "a": "policeBaton",
   "b": "street",
   "wins": 3,
   "losses": 8,
   "draws": 5
  },
  {
   "a": "street",
   "b": "unskilled",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "street",
   "b": "sumo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "sumo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "sumo",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "mingCrossbow",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "knife",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "mingSpear",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "mingSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "lordAshford",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mingSpear",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "peasant",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "taichi",
   "wins": 5,
   "losses": 8,
   "draws": 3
  },
  {
   "a": "lordAshford",
   "b": "taichi",
   "wins": 0,
   "losses": 12,
   "draws": 4
  },
  {
   "a": "joan",
   "b": "lorarius",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "shaolin",
   "wins": 5,
   "losses": 2,
   "draws": 9
  },
  {
   "a": "joan",
   "b": "shaolin",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "muayThai",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "shaolin",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "muayThai",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "shaolin",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "wokou",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "taekwondo",
   "b": "wokou",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "taekwondo",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "mandukhai",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "wokou",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "mandukhai",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mandukhai",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "kickboxer",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "steppeLancer",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "mingBrigSpear",
   "wins": 0,
   "losses": 15,
   "draws": 1
  },
  {
   "a": "mingBrigSpear",
   "b": "steppeLancer",
   "wins": 6,
   "losses": 8,
   "draws": 2
  },
  {
   "a": "kheshig",
   "b": "mingBrigSpear",
   "wins": 7,
   "losses": 6,
   "draws": 3
  },
  {
   "a": "azapArcher",
   "b": "kheshig",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "retiarius",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "retiarius",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "riot",
   "wins": 8,
   "losses": 1,
   "draws": 7
  },
  {
   "a": "azapArcher",
   "b": "riot",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "scissor",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "scissor",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "riot",
   "wins": 13,
   "losses": 2,
   "draws": 1
  },
  {
   "a": "ashigaruSpear",
   "b": "azapSpear",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "scissor",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "scissor",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "vocPikeman",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "janissary",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "vocPikeman",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "ronin",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "maximus",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "ronin",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "oyoroi",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "maximus",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "oyoroi",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "police",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "police",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "hanCrossbow",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "police",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "police",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "secutor",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "steppeArcher",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "secutor",
   "b": "steppeArcher",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "tosei",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "secutor",
   "b": "tosei",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "murmillo",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "tosei",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "tosei",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "hidalgo",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "murmillo",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "murmillo",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "thraex",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "mingGun",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "thraex",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "steppeShield",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "thraex",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "odachi",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "odachi",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "mingShield",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "wuxia",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "wuxia",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "plate",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "plate",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "kanabo",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "plate",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "pistol",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "teppo",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "teppo",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "rodelero",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "rodelero",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "plate",
   "wins": 3,
   "losses": 12,
   "draws": 1
  },
  {
   "a": "jaguar",
   "b": "kanabo",
   "wins": 2,
   "losses": 13,
   "draws": 1
  },
  {
   "a": "janissaryGun",
   "b": "mail",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "plate",
   "wins": 2,
   "losses": 13,
   "draws": 1
  },
  {
   "a": "janissaryGun",
   "b": "plate",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mail",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "janissaryGun",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "naginata",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "hammer",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "naginata",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "hammer",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "naginata",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "vocMusketeer",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "vocMusketeer",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "ladyAshford",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "naginata",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "mingThreeEyed",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "legionary",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "legionary",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "eagle",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "mexica",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "mexica",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "legionary",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "esen",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "specialForces",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "specialForces",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "sipahi",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mingCrossbow",
   "wins": 14,
   "losses": 1,
   "draws": 1
  },
  {
   "a": "ironPagoda",
   "b": "kheshig",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "ironPagoda",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "rodelero",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "plate",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "plate",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "secutor",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "plate",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "hammer",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "hammer",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "janissaryGun",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "thraex",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "kanabo",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "kanabo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "kanabo",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "mingThreeEyed",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "sipahi",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "murmillo",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "mingThreeEyed",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "mingGuandao",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "mingGuandao",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "mingGuandao",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mingGuandao",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "odachi",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "odachi",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "odachi",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "pistol",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "mingEliteGun",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "mingEliteGun",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "mingEliteGun",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "wokou",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "mingSpear",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "joan",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "joan",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "mingBrigSpear",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "tosei",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "thraex",
   "b": "tosei",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "tosei",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "tosei",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "rodelero",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "guanYu",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "guanYu",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "sipahi",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "riot",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "oyoroi",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "naginata",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "naginata",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "azapSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "crossbowman",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "thraex",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "vocPikeman",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "mail",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "maximus",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "mail",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "oyoroi",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "oyoroi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "peasant",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "teppo",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "scissor",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "scissor",
   "b": "shaolin",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "scissor",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "scissor",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "vocMusketeer",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "kheshig",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "kheshig",
   "wins": 1,
   "losses": 9,
   "draws": 6
  },
  {
   "a": "footBow",
   "b": "kheshig",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "specialForces",
   "b": "wuxia",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "specialForces",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "hidalgo",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "wuxia",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "esen",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "secutor",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "secutor",
   "b": "wokou",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "secutor",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "secutor",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "murmillo",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "murmillo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "ronin",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "steppeLancer",
   "wins": 0,
   "losses": 15,
   "draws": 1
  },
  {
   "a": "mix",
   "b": "steppeLancer",
   "wins": 0,
   "losses": 14,
   "draws": 2
  },
  {
   "a": "steppeLancer",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "steppeLancer",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "hoplomachus",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "policeBaton",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "rodelero",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "ronin",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "sipahi",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "rodelero",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mexica",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "thraex",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "thraex",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "thraex",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "thraex",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "vocPikeman",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ronin",
   "b": "vocPikeman",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "thraex",
   "b": "vocPikeman",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "vocPikeman",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "plate",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "retiarius",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "ladyAshford",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "wokou",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "centurion",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "hoplomachus",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "sumo",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "legionary",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "sumo",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "taekwondo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "street",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "lordAshford",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "secutor",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "teppo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "gaziAlp",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "sipahi",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "mingGun",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "mingGun",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "mingGun",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "mingShield",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "mingShield",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mingShield",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "mingShield",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "mingBrigSpear",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "teppo",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "mingGuandao",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mingBrigSpear",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "gaziAlp",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "lordAshford",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "crossbowman",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "steppeLancer",
   "wins": 8,
   "losses": 7,
   "draws": 1
  },
  {
   "a": "arquebus",
   "b": "mingShield",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "janissaryGun",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "arquebusier",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "mingBrigSpear",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "footBow",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "footBow",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "steppeArcher",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "taichi",
   "wins": 14,
   "losses": 0,
   "draws": 2
  },
  {
   "a": "footSpear",
   "b": "shaolin",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "footSpear",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "footSpear",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "swatShotgun",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "swatShotgun",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "swatShotgun",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "pistol",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "rodelero",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "steppeArcher",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "pistol",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "teppo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "swatShotgun",
   "b": "teppo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "street",
   "b": "teppo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "steppeArcher",
   "b": "teppo",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "mingGuandao",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "boxer",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "pistol",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "kickboxer",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "knife",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "mingSpear",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "baton",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "sipahi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "mexica",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "lordAshford",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "naginata",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "police",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "thraex",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "rodelero",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "vocPikeman",
   "wins": 1,
   "losses": 12,
   "draws": 3
  },
  {
   "a": "hoplomachus",
   "b": "riot",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "peasant",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "steppeLancer",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "legionary",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "steppeArcher",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "steppeShield",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "steppeShield",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "teppo",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "steppeShield",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "mandukhai",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "tosei",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "mandukhai",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "riot",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "oyoroi",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "guanYu",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "shaolin",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "vocMusketeer",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "specialForces",
   "b": "vocMusketeer",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "vocMusketeer",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "vocMusketeer",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "rodelero",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "rodelero",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "mexica",
   "b": "rodelero",
   "wins": 7,
   "losses": 8,
   "draws": 1
  },
  {
   "a": "mail",
   "b": "rodelero",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "maximus",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "shaolin",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "maximus",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "mingBrigSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "hammer",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "footSpear",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "steppeLancer",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "hoplomachus",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "mix",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "thraex",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "mandukhai",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "steppeLancer",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "police",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "police",
   "b": "street",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "police",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "police",
   "b": "vocPikeman",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "street",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "muayThai",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "legionary",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "ladyAshford",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "steppeArcher",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "shaolin",
   "b": "steppeArcher",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "steppeArcher",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "steppeArcher",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "murmillo",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "lorarius",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "pistol",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "tosei",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "eagle",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "police",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "mingShield",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "mexica",
   "b": "police",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mexica",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "mexica",
   "wins": 9,
   "losses": 6,
   "draws": 1
  },
  {
   "a": "mexica",
   "b": "mingBrigSpear",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "mandukhai",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "boxer",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "mingThreeEyed",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "wuxia",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "footBow",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "azapArcher",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "janissaryGun",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "guanYu",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "retiarius",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "wokou",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "retiarius",
   "wins": 4,
   "losses": 12,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "steppeShield",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "joan",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "mingSpear",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "mexica",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "mix",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "retiarius",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "centurion",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "janissaryGun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "sumo",
   "wins": 3,
   "losses": 12,
   "draws": 1
  },
  {
   "a": "sumo",
   "b": "vocMusketeer",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "sumo",
   "b": "taekwondo",
   "wins": 6,
   "losses": 6,
   "draws": 4
  },
  {
   "a": "arquebusier",
   "b": "sumo",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "janissaryGun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "azapSpear",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "guanYu",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "crossbowman",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "wokou",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "steppeLancer",
   "b": "wokou",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "wokou",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "wokou",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "mingDao",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mingDao",
   "wins": 4,
   "losses": 11,
   "draws": 1
  },
  {
   "a": "mingDao",
   "b": "mingEliteGun",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "mingDao",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "knife",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "mail",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "tosei",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "knife",
   "wins": 14,
   "losses": 1,
   "draws": 1
  },
  {
   "a": "kickboxer",
   "b": "odachi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mail",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "kickboxer",
   "wins": 12,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mingGuandao",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "teppo",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "secutor",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "muayThai",
   "wins": 14,
   "losses": 0,
   "draws": 2
  },
  {
   "a": "ashigaruBow",
   "b": "ronin",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "ronin",
   "wins": 3,
   "losses": 13,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "ronin",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "ronin",
   "b": "tosei",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "riot",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "secutor",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "naginata",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "retiarius",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "naginata",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "sumo",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "wuxia",
   "wins": 8,
   "losses": 8,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "legionary",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "lordAshford",
   "wins": 7,
   "losses": 9,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "lordAshford",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "specialForces",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "retiarius",
   "wins": 7,
   "losses": 8,
   "draws": 1
  },
  {
   "a": "jaguar",
   "b": "wuxia",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "wuxia",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "wuxia",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "wuxia",
   "wins": 6,
   "losses": 10,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "street",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "street",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "street",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "street",
   "b": "thraex",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "mingCrossbow",
   "wins": 13,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "peasant",
   "wins": 1,
   "losses": 14,
   "draws": 1
  },
  {
   "a": "mingCrossbow",
   "b": "steppeLancer",
   "wins": 0,
   "losses": 15,
   "draws": 1
  },
  {
   "a": "hoplomachus",
   "b": "mingCrossbow",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "mix",
   "wins": 15,
   "losses": 0,
   "draws": 1
  },
  {
   "a": "mandukhai",
   "b": "mix",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "mix",
   "wins": 6,
   "losses": 1,
   "draws": 9
  },
  {
   "a": "mix",
   "b": "odachi",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "policeBaton",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "policeBaton",
   "wins": 2,
   "losses": 0,
   "draws": 14
  },
  {
   "a": "esen",
   "b": "policeBaton",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "policeBaton",
   "wins": 7,
   "losses": 8,
   "draws": 1
  },
  {
   "a": "knife",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "unskilled",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "taekwondo",
   "wins": 8,
   "losses": 7,
   "draws": 1
  },
  {
   "a": "taekwondo",
   "b": "thraex",
   "wins": 1,
   "losses": 15,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "taekwondo",
   "wins": 2,
   "losses": 14,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "taekwondo",
   "wins": 11,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "taichi",
   "b": "tosei",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "taichi",
   "wins": 16,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "lorarius",
   "wins": 15,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "mix",
   "wins": 2,
   "losses": 5,
   "draws": 9
  },
  {
   "a": "lorarius",
   "b": "mandukhai",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "lorarius",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "shaolin",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "shaolin",
   "wins": 14,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "shaolin",
   "b": "wokou",
   "wins": 5,
   "losses": 11,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "shaolin",
   "wins": 11,
   "losses": 4,
   "draws": 1
  },
  {
   "a": "peasant",
   "b": "teppo",
   "wins": 0,
   "losses": 16,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "peasant",
   "wins": 9,
   "losses": 7,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "peasant",
   "wins": 10,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "plate",
   "wins": 2,
   "losses": 14,
   "draws": 0
  }
 ]
};
