// GENERATED by tools/ratings.js (6 bouts a corner against each reference, 3 against each of two nearest-rated and 2 drawn at random) — do not edit by hand; re-run the tool.
// Score = strength fitted to all those bouts at once (Bradley-Terry), Maximus held at 100: ∝ inferred K/D.
export const RATINGS = {
 "references": [
  "maximus",
  "monk"
 ],
 "bouts": 6,
 "crossBouts": 3,
 "characters": {
  "ironPagoda": {
   "title": "Wanyan Wuzhu",
   "type": "langyaShield|ironPagoda",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 750,
   "provisional": 653,
   "kd": {
    "maximus": 25,
    "monk": 7.667
   }
  },
  "hammer": {
   "title": "Gunnar Holt",
   "type": "warhammer|knight",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 1061,
   "provisional": 653,
   "kd": {
    "maximus": 25,
    "monk": 7.667
   }
  },
  "plate": {
   "title": "Sir Edric",
   "type": "longsword|knight",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 411,
   "provisional": 284,
   "kd": {
    "maximus": 2.714,
    "monk": 25
   }
  },
  "mingThreeEyed": {
   "title": "Ma Lin",
   "type": "threeEyed|mingElite",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 1706,
   "provisional": 653,
   "kd": {
    "maximus": 7.667,
    "monk": 25
   }
  },
  "kanabo": {
   "title": "Kojima Yatarō",
   "type": "kanabo|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 494,
   "provisional": 284,
   "kd": {
    "maximus": 4.2,
    "monk": 7.667
   }
  },
  "odachi": {
   "title": "Makara Naotaka",
   "type": "odachi|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 328,
   "provisional": 128,
   "kd": {
    "maximus": 2.714,
    "monk": 2.714
   }
  },
  "mingGuandao": {
   "title": "Liu Ting",
   "type": "guandao|mingElite",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 817,
   "provisional": 1393,
   "kd": {
    "maximus": 25,
    "monk": 25
   }
  },
  "mingEliteGun": {
   "title": "Wu Weizhong",
   "type": "matchlock|mingElite",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 227,
   "provisional": 284,
   "kd": {
    "maximus": 2.714,
    "monk": 25
   }
  },
  "tosei": {
   "title": "Date Masamune",
   "type": "katana|samuraiTosei",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 171,
   "provisional": 162,
   "kd": {
    "maximus": 1.364,
    "monk": 25
   }
  },
  "joan": {
   "title": "Joan of Arc",
   "type": "joan|joan",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 3,
     "losses": 9,
     "draws": 0
    }
   },
   "score": 44,
   "provisional": 17,
   "kd": {
    "maximus": 0.733,
    "monk": 0.368
   }
  },
  "guanYu": {
   "title": "Guan Yu",
   "type": "guanYu|guanYu",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 325,
   "provisional": 128,
   "kd": {
    "maximus": 1.889,
    "monk": 4.2
   }
  },
  "tametomo": {
   "title": "Minamoto no Tametomo",
   "type": "yumi|oyoroi",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 338,
   "provisional": 653,
   "kd": {
    "maximus": 25,
    "monk": 7.667
   }
  },
  "naginata": {
   "title": "Tomoe Gozen",
   "type": "naginata|samurai",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 218,
   "provisional": 406,
   "kd": {
    "maximus": 4.2,
    "monk": 25
   }
  },
  "archer": {
   "title": "Nasu no Yoichi",
   "type": "bow|samurai",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 110,
   "provisional": 128,
   "kd": {
    "maximus": 1.364,
    "monk": 7.667
   }
  },
  "mail": {
   "title": "Sir Aldous",
   "type": "longsword|knightMail",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 117,
   "provisional": 406,
   "kd": {
    "maximus": 4.2,
    "monk": 25
   }
  },
  "oyoroi": {
   "title": "Takeda Shingen",
   "type": "katana|samurai",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 139,
   "provisional": 83,
   "kd": {
    "maximus": 0.733,
    "monk": 7.667
   }
  },
  "templar": {
   "title": "Knights Templar",
   "type": "templar|templar",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 292,
   "provisional": 162,
   "kd": {
    "maximus": 1.364,
    "monk": 25
   }
  },
  "scissor": {
   "title": "Astacius",
   "type": "scissor|scissor",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 176,
   "provisional": 83,
   "kd": {
    "maximus": 1,
    "monk": 4.2
   }
  },
  "kheshig": {
   "title": "Subutai",
   "type": "spear|kheshig",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 68,
   "provisional": 55,
   "kd": {
    "maximus": 0.529,
    "monk": 4.2
   }
  },
  "specialForces": {
   "title": "SSgt. Ryan Brooks",
   "type": "rifle|specialForces",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 4027,
   "provisional": 1393,
   "kd": {
    "maximus": 25,
    "monk": 25
   }
  },
  "esen": {
   "title": "Esen Taishi",
   "type": "maceShield|steppeHeavy",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 1178,
   "provisional": 1393,
   "kd": {
    "maximus": 25,
    "monk": 25
   }
  },
  "secutor": {
   "title": "Flamma",
   "type": "secutor|secutor",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 142,
   "provisional": 210,
   "kd": {
    "maximus": 4.2,
    "monk": 4.2
   }
  },
  "murmillo": {
   "title": "Verus",
   "type": "murmillo|murmillo",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 154,
   "provisional": 162,
   "kd": {
    "maximus": 1.889,
    "monk": 7.667
   }
  },
  "steppeLancer": {
   "title": "Temür",
   "type": "spear|steppeHeavy",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 55,
   "provisional": 37,
   "kd": {
    "maximus": 0.13,
    "monk": 7.667
   }
  },
  "sipahi": {
   "title": "Davud the sipahi",
   "type": "maceShield|ottomanHeavy",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 1786,
   "provisional": 1393,
   "kd": {
    "maximus": 25,
    "monk": 25
   }
  },
  "hidalgo": {
   "title": "Hernán Cortés",
   "type": "espada|conquistadorPlate",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 178,
   "provisional": 210,
   "kd": {
    "maximus": 1.889,
    "monk": 25
   }
  },
  "hoplomachus": {
   "title": "Priscus",
   "type": "hoplomachus|hoplomachus",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 272,
   "provisional": 210,
   "kd": {
    "maximus": 2.714,
    "monk": 7.667
   }
  },
  "thraex": {
   "title": "Spartacus",
   "type": "thraex|thraex",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 172,
   "provisional": 284,
   "kd": {
    "maximus": 4.2,
    "monk": 7.667
   }
  },
  "vocPikeman": {
   "title": "Jan de Vries",
   "type": "spear|conquistadorPlate",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 10,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 80,
   "provisional": 45,
   "kd": {
    "maximus": 0.238,
    "monk": 7.667
   }
  },
  "centurion": {
   "title": "Marcus Caelius",
   "type": "centurion|centurion",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 108,
   "provisional": 128,
   "kd": {
    "maximus": 1.889,
    "monk": 4.2
   }
  },
  "legionary": {
   "title": "Gaius Valerius Crispus",
   "type": "legionary|legionary",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 360,
   "provisional": 1393,
   "kd": {
    "maximus": 25,
    "monk": 25
   }
  },
  "gaziAlp": {
   "title": "Turgut Alp",
   "type": "saberShield|gaziAlp",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 357,
   "provisional": 653,
   "kd": {
    "maximus": 25,
    "monk": 7.667
   }
  },
  "mingShield": {
   "title": "Chen Bao",
   "type": "swordShield|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 479,
   "provisional": 284,
   "kd": {
    "maximus": 2.714,
    "monk": 25
   }
  },
  "mingGun": {
   "title": "Zhao Liu",
   "type": "matchlock|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 186,
   "provisional": 162,
   "kd": {
    "maximus": 1.889,
    "monk": 7.667
   }
  },
  "mingBrigSpear": {
   "title": "Sun Qi",
   "type": "spear|mingBrigandine",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 41,
   "provisional": 37,
   "kd": {
    "maximus": 0.04,
    "monk": 25
   }
  },
  "arquebus": {
   "title": "Hans Brenner",
   "type": "matchlock|footman",
   "records": {
    "maximus": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 660,
   "provisional": 1393,
   "kd": {
    "maximus": 25,
    "monk": 25
   }
  },
  "footBow": {
   "title": "Tom Fletcher",
   "type": "bow|footman",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 159,
   "provisional": 162,
   "kd": {
    "maximus": 1.364,
    "monk": 25
   }
  },
  "crossbowman": {
   "title": "Ottone Doria",
   "type": "crossbow|footman",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 124,
   "provisional": 210,
   "kd": {
    "maximus": 1.889,
    "monk": 25
   }
  },
  "footSpear": {
   "title": "Will Ward",
   "type": "spear|footman",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 74,
   "provisional": 83,
   "kd": {
    "maximus": 0.733,
    "monk": 7.667
   }
  },
  "swatShotgun": {
   "title": "Cpl. Marcus Hale",
   "type": "shotgun|swat",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 867,
   "provisional": 284,
   "kd": {
    "maximus": 2.714,
    "monk": 25
   }
  },
  "pistol": {
   "title": "Sgt. Dana Cole",
   "type": "handgun|swat",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 0,
     "draws": 1
    }
   },
   "score": 259,
   "provisional": 336,
   "kd": {
    "maximus": 4.2,
    "monk": 12
   }
  },
  "teppo": {
   "title": "Suzuki Magoichi",
   "type": "matchlock|ashigaru",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 185,
   "provisional": 406,
   "kd": {
    "maximus": 4.2,
    "monk": 25
   }
  },
  "ashigaruBow": {
   "title": "Sakuzaemon",
   "type": "bow|ashigaru",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 77,
   "provisional": 128,
   "kd": {
    "maximus": 1.364,
    "monk": 7.667
   }
  },
  "ashigaruSpear": {
   "title": "Gonbei",
   "type": "yari|ashigaru",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 54,
   "provisional": 83,
   "kd": {
    "maximus": 0.733,
    "monk": 7.667
   }
  },
  "baton": {
   "title": "Officer Reyes",
   "type": "baton|swat",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 6,
     "losses": 0,
     "draws": 6
    }
   },
   "score": 38,
   "provisional": 21,
   "kd": {
    "maximus": 0.04,
    "monk": 2.714
   }
  },
  "hanCrossbow": {
   "title": "Li Ling",
   "type": "nu|hanSoldier",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 88,
   "provisional": 83,
   "kd": {
    "maximus": 0.529,
    "monk": 25
   }
  },
  "riot": {
   "title": "Officer Dale Burke",
   "type": "riot|riot",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 7,
     "draws": 1
    },
    "monk": {
     "wins": 6,
     "losses": 3,
     "draws": 3
    }
   },
   "score": 31,
   "provisional": 37,
   "kd": {
    "maximus": 0.625,
    "monk": 1.6
   }
  },
  "steppeShield": {
   "title": "Ganbold",
   "type": "saberShield|steppeMedium",
   "records": {
    "maximus": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 208,
   "provisional": 162,
   "kd": {
    "maximus": 1.889,
    "monk": 7.667
   }
  },
  "mandukhai": {
   "title": "Mandukhai Khatun",
   "type": "saber|steppeMedium",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 36,
   "provisional": 21,
   "kd": {
    "maximus": 0.04,
    "monk": 2.714
   }
  },
  "arquebusier": {
   "title": "Diego de Ordaz",
   "type": "matchlock|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 264,
   "provisional": 406,
   "kd": {
    "maximus": 4.2,
    "monk": 25
   }
  },
  "vocMusketeer": {
   "title": "Hans Pedel",
   "type": "matchlock|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 363,
   "provisional": 406,
   "kd": {
    "maximus": 4.2,
    "monk": 25
   }
  },
  "rodelero": {
   "title": "Bernal Díaz",
   "type": "espadaRodela|conquistadorQuilted",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 171,
   "provisional": 406,
   "kd": {
    "maximus": 7.667,
    "monk": 7.667
   }
  },
  "eagle": {
   "title": "Cuauhtémoc",
   "type": "macuahuitl|mexicaElite",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 398,
   "provisional": 653,
   "kd": {
    "maximus": 7.667,
    "monk": 25
   }
  },
  "jaguar": {
   "title": "Ocelotl",
   "type": "tepoztopilli|mexicaElite",
   "records": {
    "maximus": {
     "wins": 7,
     "losses": 5,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 100,
   "provisional": 162,
   "kd": {
    "maximus": 1.364,
    "monk": 25
   }
  },
  "maximus": {
   "title": "Maximus",
   "type": "maximus|maximus",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 100,
   "provisional": 100,
   "kd": {
    "maximus": 1,
    "monk": 25
   }
  },
  "ladyAshford": {
   "title": "Lady Ashford",
   "type": "revolver|victorianLady",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 439,
   "provisional": 406,
   "kd": {
    "maximus": 7.667,
    "monk": 7.667
   }
  },
  "mexica": {
   "title": "Yaotl",
   "type": "macuahuitl|mexicaWarrior",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 322,
   "provisional": 653,
   "kd": {
    "maximus": 7.667,
    "monk": 25
   }
  },
  "janissaryGun": {
   "title": "Mehmed Çavuş",
   "type": "matchlock|janissary",
   "records": {
    "maximus": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 317,
   "provisional": 406,
   "kd": {
    "maximus": 7.667,
    "monk": 7.667
   }
  },
  "police": {
   "title": "Officer Mike Kowalski",
   "type": "handgun|police",
   "records": {
    "maximus": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 135,
   "provisional": 284,
   "kd": {
    "maximus": 4.2,
    "monk": 7.667
   }
  },
  "wuxia": {
   "title": "Pei Min",
   "type": "wuxia|wuxia",
   "records": {
    "maximus": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 182,
   "provisional": 284,
   "kd": {
    "maximus": 2.714,
    "monk": 25
   }
  },
  "commodus": {
   "title": "Commodus",
   "type": "commodus|commodus",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 91,
   "provisional": 83,
   "kd": {
    "maximus": 0.733,
    "monk": 7.667
   }
  },
  "steppeArcher": {
   "title": "Bayar",
   "type": "steppeBow|steppeLight",
   "records": {
    "maximus": {
     "wins": 5,
     "losses": 7,
     "draws": 0
    },
    "monk": {
     "wins": 11,
     "losses": 1,
     "draws": 0
    }
   },
   "score": 87,
   "provisional": 83,
   "kd": {
    "maximus": 0.733,
    "monk": 7.667
   }
  },
  "ronin": {
   "title": "Miyamoto Musashi",
   "type": "katana|ronin",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 130,
   "provisional": 128,
   "kd": {
    "maximus": 1,
    "monk": 25
   }
  },
  "janissary": {
   "title": "Ulubatlı Hasan",
   "type": "yatagan|janissary",
   "records": {
    "maximus": {
     "wins": 6,
     "losses": 6,
     "draws": 0
    },
    "monk": {
     "wins": 12,
     "losses": 0,
     "draws": 0
    }
   },
   "score": 91,
   "provisional": 128,
   "kd": {
    "maximus": 1,
    "monk": 25
   }
  },
  "azapArcher": {
   "title": "Ali the azap",
   "type": "steppeBow|azap",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 10,
     "draws": 0
    },
    "monk": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 39,
   "provisional": 31,
   "kd": {
    "maximus": 0.238,
    "monk": 2.714
   }
  },
  "azapSpear": {
   "title": "Yusuf the azap",
   "type": "spear|azap",
   "records": {
    "maximus": {
     "wins": 4,
     "losses": 8,
     "draws": 0
    },
    "monk": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 42,
   "provisional": 45,
   "kd": {
    "maximus": 0.529,
    "monk": 2.714
   }
  },
  "boxer": {
   "title": "Marcus \"The Wall\"",
   "type": "boxing|boxing",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 8,
     "losses": 4,
     "draws": 0
    }
   },
   "score": 43,
   "provisional": 31,
   "kd": {
    "maximus": 0.368,
    "monk": 1.889
   }
  },
  "retiarius": {
   "title": "Kalendio",
   "type": "retiarius|retiarius",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 45,
   "provisional": 45,
   "kd": {
    "maximus": 0.368,
    "monk": 4.2
   }
  },
  "brawler": {
   "title": "Hank Doyle",
   "type": "clinchBrawl|mma",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 1,
     "draws": 1
    }
   },
   "score": 26,
   "provisional": 50,
   "kd": {
    "maximus": 0.368,
    "monk": 5.5
   }
  },
  "wokou": {
   "title": "Wang Zhi",
   "type": "dao|wokou",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 28,
   "provisional": 25,
   "kd": {
    "maximus": 0.13,
    "monk": 2.714
   }
  },
  "mingDao": {
   "title": "Zhang San",
   "type": "dao|mingGarrison",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 43,
   "provisional": 25,
   "kd": {
    "maximus": 0.04,
    "monk": 4.2
   }
  },
  "taekwondo": {
   "title": "Kim Min-jun",
   "type": "taekwondo|dobok",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 7,
     "losses": 1,
     "draws": 4
    }
   },
   "score": 25,
   "provisional": 21,
   "kd": {
    "maximus": 0.04,
    "monk": 2.714
   }
  },
  "lordAshford": {
   "title": "Lord Ashford",
   "type": "rapier|victorianGent",
   "records": {
    "maximus": {
     "wins": 3,
     "losses": 9,
     "draws": 0
    },
    "monk": {
     "wins": 3,
     "losses": 9,
     "draws": 0
    }
   },
   "score": 19,
   "provisional": 11,
   "kd": {
    "maximus": 0.368,
    "monk": 0.368
   }
  },
  "peasant": {
   "title": "Hob Miller",
   "type": "pitchfork|commoner",
   "records": {
    "maximus": {
     "wins": 2,
     "losses": 10,
     "draws": 0
    },
    "monk": {
     "wins": 3,
     "losses": 8,
     "draws": 1
    }
   },
   "score": 11,
   "provisional": 9.8,
   "kd": {
    "maximus": 0.238,
    "monk": 0.444
   }
  },
  "sumo": {
   "title": "Takanohana",
   "type": "sumo|sumo",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 2,
     "losses": 8,
     "draws": 2
    }
   },
   "score": 12,
   "provisional": 6.7,
   "kd": {
    "maximus": 0.13,
    "monk": 0.368
   }
  },
  "shaolin": {
   "title": "Tanzong",
   "type": "staff|monk",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 4,
     "losses": 4,
     "draws": 4
    }
   },
   "score": 16,
   "provisional": 14,
   "kd": {
    "maximus": 0.04,
    "monk": 1
   }
  },
  "taichi": {
   "title": "Chen Fake",
   "type": "taichi|kungfu",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 7,
     "losses": 4,
     "draws": 1
    }
   },
   "score": 12,
   "provisional": 15,
   "kd": {
    "maximus": 0.04,
    "monk": 1.6
   }
  },
  "kickboxer": {
   "title": "Leo Quickhands",
   "type": "kickboxing|boxing",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 1,
     "draws": 1
    }
   },
   "score": 20,
   "provisional": 28,
   "kd": {
    "maximus": 0.04,
    "monk": 5.5
   }
  },
  "muayThai": {
   "title": "Ana Ruiz",
   "type": "muayThai|boxing",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 9,
     "losses": 3,
     "draws": 0
    }
   },
   "score": 15,
   "provisional": 21,
   "kd": {
    "maximus": 0.04,
    "monk": 2.714
   }
  },
  "bat": {
   "title": "Tony Marchetti",
   "type": "bat|thug",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 4,
     "losses": 8,
     "draws": 0
    }
   },
   "score": 14,
   "provisional": 8.7,
   "kd": {
    "maximus": 0.13,
    "monk": 0.529
   }
  },
  "mix": {
   "title": "Kai Moana",
   "type": "mix|sports",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 10,
     "losses": 2,
     "draws": 0
    }
   },
   "score": 25,
   "provisional": 31,
   "kd": {
    "maximus": 0.13,
    "monk": 4.2
   }
  },
  "knife": {
   "title": "Ryo Kanda",
   "type": "knife|yakuza",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 7,
     "losses": 5,
     "draws": 0
    }
   },
   "score": 15,
   "provisional": 17,
   "kd": {
    "maximus": 0.13,
    "monk": 1.364
   }
  },
  "mingSpear": {
   "title": "Wang Er",
   "type": "spear|mingGarrison",
   "records": {
    "maximus": {
     "wins": 1,
     "losses": 11,
     "draws": 0
    },
    "monk": {
     "wins": 5,
     "losses": 7,
     "draws": 0
    }
   },
   "score": 11,
   "provisional": 11,
   "kd": {
    "maximus": 0.13,
    "monk": 0.733
   }
  },
  "lorarius": {
   "title": "Felix the lorarius",
   "type": "whip|lorarius",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 3,
     "losses": 1,
     "draws": 8
    }
   },
   "score": 17,
   "provisional": 14,
   "kd": {
    "maximus": 0.04,
    "monk": 1.364
   }
  },
  "street": {
   "title": "Vinnie Russo",
   "type": "street|casual",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 0,
     "losses": 10,
     "draws": 2
    }
   },
   "score": 5.7,
   "provisional": 2.1,
   "kd": {
    "maximus": 0.04,
    "monk": 0.13
   }
  },
  "mingCrossbow": {
   "title": "Li Si",
   "type": "nu|mingGarrison",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 0,
     "losses": 10,
     "draws": 2
    }
   },
   "score": 2.7,
   "provisional": 2.1,
   "kd": {
    "maximus": 0.04,
    "monk": 0.13
   }
  },
  "policeBaton": {
   "title": "Officer Ana Ruiz",
   "type": "baton|police",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    }
   },
   "score": 3.2,
   "provisional": 1,
   "kd": {
    "maximus": 0.04,
    "monk": 0.04
   }
  },
  "unskilled": {
   "title": "Wat Tyler",
   "type": "unskilled|commoner",
   "records": {
    "maximus": {
     "wins": 0,
     "losses": 12,
     "draws": 0
    },
    "monk": {
     "wins": 0,
     "losses": 11,
     "draws": 1
    }
   },
   "score": 1.8,
   "provisional": 1.6,
   "kd": {
    "maximus": 0.04,
    "monk": 0.083
   }
  }
 },
 "types": {
  "langyaShield|ironPagoda": 750,
  "warhammer|knight": 1061,
  "longsword|knight": 411,
  "threeEyed|mingElite": 1706,
  "kanabo|samuraiTosei": 494,
  "odachi|samuraiTosei": 328,
  "guandao|mingElite": 817,
  "matchlock|mingElite": 227,
  "katana|samuraiTosei": 171,
  "joan|joan": 44,
  "guanYu|guanYu": 325,
  "yumi|oyoroi": 338,
  "naginata|samurai": 218,
  "bow|samurai": 110,
  "longsword|knightMail": 117,
  "katana|samurai": 139,
  "templar|templar": 292,
  "scissor|scissor": 176,
  "spear|kheshig": 68,
  "rifle|specialForces": 4027,
  "maceShield|steppeHeavy": 1178,
  "secutor|secutor": 142,
  "murmillo|murmillo": 154,
  "spear|steppeHeavy": 55,
  "maceShield|ottomanHeavy": 1786,
  "espada|conquistadorPlate": 178,
  "hoplomachus|hoplomachus": 272,
  "thraex|thraex": 172,
  "spear|conquistadorPlate": 80,
  "centurion|centurion": 108,
  "legionary|legionary": 360,
  "saberShield|gaziAlp": 357,
  "swordShield|mingBrigandine": 479,
  "matchlock|mingBrigandine": 186,
  "spear|mingBrigandine": 41,
  "matchlock|footman": 660,
  "bow|footman": 159,
  "crossbow|footman": 124,
  "spear|footman": 74,
  "shotgun|swat": 867,
  "handgun|swat": 259,
  "matchlock|ashigaru": 185,
  "bow|ashigaru": 77,
  "yari|ashigaru": 54,
  "baton|swat": 38,
  "nu|hanSoldier": 88,
  "riot|riot": 31,
  "saberShield|steppeMedium": 208,
  "saber|steppeMedium": 36,
  "matchlock|conquistadorQuilted": 309,
  "espadaRodela|conquistadorQuilted": 171,
  "macuahuitl|mexicaElite": 398,
  "tepoztopilli|mexicaElite": 100,
  "maximus|maximus": 100,
  "revolver|victorianLady": 439,
  "macuahuitl|mexicaWarrior": 322,
  "matchlock|janissary": 317,
  "handgun|police": 135,
  "wuxia|wuxia": 182,
  "commodus|commodus": 91,
  "steppeBow|steppeLight": 87,
  "katana|ronin": 130,
  "yatagan|janissary": 91,
  "steppeBow|azap": 39,
  "spear|azap": 42,
  "boxing|boxing": 43,
  "retiarius|retiarius": 45,
  "clinchBrawl|mma": 26,
  "dao|wokou": 28,
  "dao|mingGarrison": 43,
  "taekwondo|dobok": 25,
  "rapier|victorianGent": 19,
  "pitchfork|commoner": 11,
  "sumo|sumo": 12,
  "staff|monk": 16,
  "taichi|kungfu": 12,
  "kickboxing|boxing": 20,
  "muayThai|boxing": 15,
  "bat|thug": 14,
  "mix|sports": 25,
  "knife|yakuza": 15,
  "spear|mingGarrison": 11,
  "whip|lorarius": 17,
  "street|casual": 5.7,
  "nu|mingGarrison": 2.7,
  "baton|police": 3.2,
  "unskilled|commoner": 1.8
 },
 "cross": [
  {
   "a": "policeBaton",
   "b": "unskilled",
   "wins": 4,
   "losses": 0,
   "draws": 2
  },
  {
   "a": "policeBaton",
   "b": "street",
   "wins": 0,
   "losses": 3,
   "draws": 3
  },
  {
   "a": "street",
   "b": "unskilled",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "unskilled",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "street",
   "wins": 0,
   "losses": 5,
   "draws": 1
  },
  {
   "a": "bat",
   "b": "sumo",
   "wins": 2,
   "losses": 3,
   "draws": 1
  },
  {
   "a": "peasant",
   "b": "sumo",
   "wins": 2,
   "losses": 1,
   "draws": 3
  },
  {
   "a": "bat",
   "b": "peasant",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "lordAshford",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "peasant",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "peasant",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "mingSpear",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "shaolin",
   "wins": 1,
   "losses": 1,
   "draws": 4
  },
  {
   "a": "lorarius",
   "b": "taichi",
   "wins": 1,
   "losses": 1,
   "draws": 4
  },
  {
   "a": "shaolin",
   "b": "taichi",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "taichi",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "knife",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "taichi",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "mandukhai",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "taekwondo",
   "wins": 1,
   "losses": 0,
   "draws": 5
  },
  {
   "a": "mandukhai",
   "b": "taekwondo",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "muayThai",
   "wins": 5,
   "losses": 0,
   "draws": 1
  },
  {
   "a": "mandukhai",
   "b": "muayThai",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "wokou",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "wokou",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mingDao",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "kickboxer",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "kickboxer",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "boxer",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "mix",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "mix",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "steppeLancer",
   "wins": 3,
   "losses": 1,
   "draws": 2
  },
  {
   "a": "riot",
   "b": "steppeLancer",
   "wins": 0,
   "losses": 5,
   "draws": 1
  },
  {
   "a": "mingBrigSpear",
   "b": "riot",
   "wins": 4,
   "losses": 0,
   "draws": 2
  },
  {
   "a": "azapSpear",
   "b": "vocPikeman",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "vocPikeman",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "retiarius",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "vocPikeman",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "brawler",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "kheshig",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "vocPikeman",
   "wins": 1,
   "losses": 2,
   "draws": 3
  },
  {
   "a": "oyoroi",
   "b": "scissor",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "oyoroi",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "scissor",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "oyoroi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "scissor",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "oyoroi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hanCrossbow",
   "b": "scissor",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "oyoroi",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "scissor",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "oyoroi",
   "b": "steppeArcher",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "scissor",
   "b": "steppeArcher",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "oyoroi",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "scissor",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "odachi",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "odachi",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "guanYu",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "odachi",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "guanYu",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "odachi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "guanYu",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "ronin",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "ronin",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "odachi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "janissary",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "templar",
   "b": "tosei",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "tosei",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "templar",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "tosei",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "templar",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "tosei",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "templar",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "tosei",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "templar",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "tosei",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "templar",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "secutor",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "secutor",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "hoplomachus",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "secutor",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "hidalgo",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "plate",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "plate",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "mingEliteGun",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "thraex",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "thraex",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingShield",
   "b": "plate",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "mingShield",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "police",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "police",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "plate",
   "b": "wuxia",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "wuxia",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "plate",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "pistol",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "naginata",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "teppo",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "teppo",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "naginata",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "mail",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "vocMusketeer",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "rodelero",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "rodelero",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "naginata",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "mail",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "naginata",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "mail",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "ironPagoda",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mingThreeEyed",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "mingThreeEyed",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "tametomo",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "tametomo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "ironPagoda",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "hammer",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "ironPagoda",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "hammer",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mexica",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "mexica",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "specialForces",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "mingGuandao",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "specialForces",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "sipahi",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "specialForces",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "mingGuandao",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "legionary",
   "b": "specialForces",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "mingGuandao",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "specialForces",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "ironPagoda",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "scissor",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "mandukhai",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "vocMusketeer",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "plate",
   "wins": 1,
   "losses": 4,
   "draws": 1
  },
  {
   "a": "oyoroi",
   "b": "plate",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "specialForces",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "odachi",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "kanabo",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "kanabo",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "police",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "odachi",
   "b": "sipahi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingGuandao",
   "b": "murmillo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "mingGuandao",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "scissor",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "mingEliteGun",
   "b": "vocPikeman",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "kanabo",
   "b": "tosei",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "steppeLancer",
   "b": "tosei",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "secutor",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "joan",
   "b": "templar",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "guanYu",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "guanYu",
   "b": "mandukhai",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "tametomo",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "shaolin",
   "b": "tametomo",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingThreeEyed",
   "b": "naginata",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "naginata",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "plate",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "mail",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "peasant",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "oyoroi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "oyoroi",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "templar",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "templar",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "scissor",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "scissor",
   "b": "vocPikeman",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "sipahi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "kheshig",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "police",
   "b": "specialForces",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "specialForces",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "esen",
   "b": "steppeLancer",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "esen",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mail",
   "b": "secutor",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "secutor",
   "b": "taekwondo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "secutor",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "murmillo",
   "b": "specialForces",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "steppeLancer",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "steppeLancer",
   "wins": 4,
   "losses": 1,
   "draws": 1
  },
  {
   "a": "mingBrigSpear",
   "b": "sipahi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "sipahi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "hidalgo",
   "wins": 4,
   "losses": 0,
   "draws": 2
  },
  {
   "a": "hidalgo",
   "b": "rodelero",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "steppeLancer",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "hoplomachus",
   "b": "police",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "thraex",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "thraex",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "unskilled",
   "b": "vocPikeman",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "vocPikeman",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "lordAshford",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "policeBaton",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "legionary",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "legionary",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "gaziAlp",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "gaziAlp",
   "b": "police",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "mingShield",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "mingShield",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingGun",
   "b": "taekwondo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mingGun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "wokou",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "mingBrigSpear",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "street",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "arquebus",
   "b": "hoplomachus",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "footBow",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "footBow",
   "b": "kickboxer",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "retiarius",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "crossbowman",
   "b": "hanCrossbow",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "retiarius",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "footSpear",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "swatShotgun",
   "b": "vocPikeman",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "pistol",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "sipahi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "teppo",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "teppo",
   "b": "unskilled",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "mix",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "ashigaruBow",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "hoplomachus",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "ashigaruSpear",
   "b": "footBow",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "knife",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "baton",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 5,
   "draws": 1
  },
  {
   "a": "hanCrossbow",
   "b": "peasant",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "centurion",
   "b": "hanCrossbow",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "vocMusketeer",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "riot",
   "b": "wuxia",
   "wins": 1,
   "losses": 4,
   "draws": 1
  },
  {
   "a": "sipahi",
   "b": "steppeShield",
   "wins": 5,
   "losses": 0,
   "draws": 1
  },
  {
   "a": "steppeShield",
   "b": "tametomo",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "ironPagoda",
   "b": "mandukhai",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "mingCrossbow",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "mingShield",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "arquebusier",
   "b": "peasant",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "peasant",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "vocMusketeer",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "rodelero",
   "b": "secutor",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "hammer",
   "b": "rodelero",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "street",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "ronin",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "jaguar",
   "b": "ladyAshford",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "jaguar",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "maximus",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "murmillo",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "ladyAshford",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "ladyAshford",
   "b": "murmillo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "mexica",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "mexica",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "muayThai",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "taichi",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "pistol",
   "b": "police",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "police",
   "b": "teppo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "sipahi",
   "b": "wuxia",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "ronin",
   "b": "wuxia",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "janissaryGun",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "commodus",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "eagle",
   "b": "steppeArcher",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "police",
   "b": "steppeArcher",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "ronin",
   "b": "shaolin",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "ronin",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "janissary",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "janissary",
   "b": "steppeShield",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "azapArcher",
   "b": "odachi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "shaolin",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "azapSpear",
   "b": "legionary",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "taichi",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "boxer",
   "b": "thraex",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "thraex",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "retiarius",
   "b": "secutor",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "mingShield",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "brawler",
   "b": "footSpear",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "wokou",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mandukhai",
   "b": "wokou",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "mingGun",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "commodus",
   "b": "mingDao",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "ashigaruBow",
   "b": "taekwondo",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "janissaryGun",
   "b": "taekwondo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "lordAshford",
   "b": "street",
   "wins": 4,
   "losses": 0,
   "draws": 2
  },
  {
   "a": "lordAshford",
   "b": "policeBaton",
   "wins": 5,
   "losses": 0,
   "draws": 1
  },
  {
   "a": "ashigaruSpear",
   "b": "peasant",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "peasant",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "steppeShield",
   "b": "sumo",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingBrigSpear",
   "b": "sumo",
   "wins": 3,
   "losses": 3,
   "draws": 0
  },
  {
   "a": "rodelero",
   "b": "shaolin",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "shaolin",
   "b": "steppeShield",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "archer",
   "b": "taichi",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "taichi",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "mexica",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "kickboxer",
   "b": "thraex",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "muayThai",
   "b": "taichi",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "footSpear",
   "b": "muayThai",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "muayThai",
   "wins": 4,
   "losses": 2,
   "draws": 0
  },
  {
   "a": "bat",
   "b": "janissaryGun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "odachi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "mix",
   "b": "steppeArcher",
   "wins": 2,
   "losses": 4,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "swatShotgun",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "knife",
   "b": "taekwondo",
   "wins": 1,
   "losses": 5,
   "draws": 0
  },
  {
   "a": "mingDao",
   "b": "mingSpear",
   "wins": 5,
   "losses": 1,
   "draws": 0
  },
  {
   "a": "mingSpear",
   "b": "steppeArcher",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "lorarius",
   "b": "sipahi",
   "wins": 0,
   "losses": 4,
   "draws": 2
  },
  {
   "a": "lorarius",
   "b": "wuxia",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "street",
   "b": "taichi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "naginata",
   "b": "street",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "maximus",
   "b": "mingCrossbow",
   "wins": 6,
   "losses": 0,
   "draws": 0
  },
  {
   "a": "mingCrossbow",
   "b": "tametomo",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "policeBaton",
   "b": "steppeArcher",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "policeBaton",
   "b": "sipahi",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "unskilled",
   "b": "vocMusketeer",
   "wins": 0,
   "losses": 6,
   "draws": 0
  },
  {
   "a": "hidalgo",
   "b": "unskilled",
   "wins": 6,
   "losses": 0,
   "draws": 0
  }
 ]
};
